// Copyright 2026 Picomisu contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by tools/generate-pico-api-fixture.py; do not edit.
package org.picomisu.runtime;

import android.content.ComponentName;
import android.os.Bundle;
import android.os.IBinder;
import android.os.Parcel;
import android.os.Parcelable;

import java.io.PrintStream;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Proxy;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * Wire-format scenarios for the PICO framework AIDL interfaces and parcelables. The same
 * probe JAR runs on the factory and the Source framework; lines "audio-api key=value" are
 * compared by tools/compare-pico-api-runtime.py.
 */
public final class AudioApiFixture {
    static final int EXPECTED_LINES = 346;
    private static PrintStream sOut;
    private static int sLines;
    private static String sRecorded;

    private AudioApiFixture() {}

    public static void main(String[] args) throws Exception {
        System.out.println("audio-api-fixture lines=" + run(System.out));
    }

    static void emit(String key, Object value) {
        sOut.println("audio-api " + key + "=" + value);
        sLines++;
    }

    static void record(String name, Object[] args) {
        sRecorded = name + describe(args);
    }

    private static final char[] DIGITS = "0123456789abcdef".toCharArray();

    static String hex(Parcel parcel) {
        byte[] bytes = parcel.marshall();
        char[] text = new char[bytes.length * 2];
        for (int i = 0; i < bytes.length; ++i) {
            text[2 * i] = DIGITS[(bytes[i] >> 4) & 0xf];
            text[2 * i + 1] = DIGITS[bytes[i] & 0xf];
        }
        return new String(text);
    }

    static String describe(Object value) {
        if (value == null) return "null";
        if (value instanceof Object[]) {
            StringBuilder text = new StringBuilder("[");
            for (Object item : (Object[]) value) text.append(describe(item)).append(',');
            return text.append(']').toString();
        }
        if (value instanceof int[]) return Arrays.toString((int[]) value);
        if (value instanceof long[]) return Arrays.toString((long[]) value);
        if (value instanceof byte[]) return Arrays.toString((byte[]) value);
        if (value instanceof boolean[]) return Arrays.toString((boolean[]) value);
        if (value instanceof float[]) return Arrays.toString((float[]) value);
        if (value instanceof Bundle) {
            Bundle bundle = (Bundle) value;
            List<String> keys = new ArrayList<>(bundle.keySet());
            keys.sort(null);
            StringBuilder text = new StringBuilder("Bundle{");
            for (String key : keys) text.append(key).append('=').append(bundle.get(key)).append(';');
            return text.append('}').toString();
        }
        if (value instanceof Parcelable) {
            Parcel parcel = Parcel.obtain();
            ((Parcelable) value).writeToParcel(parcel, 0);
            String result = value.getClass().getName() + ":" + hex(parcel);
            parcel.recycle();
            return result;
        }
        return String.valueOf(value);
    }

    static Object argument(Class<?> type, int index) {
        if (type == int.class) return 0x11223340 + index;
        if (type == long.class) return 0x1122334455667700L + index;
        if (type == boolean.class) return index % 2 == 0;
        if (type == byte.class) return (byte) (0x40 + index);
        if (type == float.class) return 1.5f + index;
        if (type == double.class) return 2.5d + index;
        if (type == String.class) return "s" + index;
        if (type == String[].class) return new String[] {"a" + index, "b" + index};
        if (type == int[].class) return new int[] {index, index + 1};
        if (type == Bundle.class) {
            Bundle bundle = new Bundle();
            bundle.putString("k" + index, "v" + index);
            return bundle;
        }
        if (type == ComponentName.class) return new ComponentName("org.picomisu", "org.picomisu.C" + index);
        if (type == byte[].class) return new byte[] {(byte) index, (byte) 0x5a};
        // Out arrays must be non-null: Parcel.readXxxArray(null) aborts in native code.
        if (type.isArray()) return java.lang.reflect.Array.newInstance(type.getComponentType(), 2);
        return null;
    }

    /** IBinder that records transactions and answers with an empty no-exception reply. */
    static final class Wire {
        int code;
        int flags;
        String data;
        byte[] raw;

        IBinder binder() {
            return (IBinder) Proxy.newProxyInstance(IBinder.class.getClassLoader(),
                    new Class<?>[] {IBinder.class}, (proxy, method, values) -> {
                        switch (method.getName()) {
                            case "transact": {
                                code = (Integer) values[0];
                                flags = (Integer) values[3];
                                Parcel in = (Parcel) values[1];
                                raw = in.marshall();
                                data = hex(in);
                                Parcel reply = (Parcel) values[2];
                                if (reply != null) {
                                    reply.writeNoException();
                                    for (int i = 0; i < 16; ++i) reply.writeInt(0);
                                    reply.setDataPosition(0);
                                }
                                return true;
                            }
                            case "queryLocalInterface": return null;
                            case "isBinderAlive": case "pingBinder": return true;
                            case "linkToDeath": return null;
                            case "unlinkToDeath": return true;
                            case "getInterfaceDescriptor": return "wire";
                            default: return null;
                        }
                    });
        }
    }

    static int run(PrintStream out) throws Exception {
        sOut = out;
        sLines = 0;
        for (Object[] entry : REGISTRY) {
            interfaceScenarios((String) entry[0], (Class<?>) entry[1], (Integer) entry[2]);
        }
        for (String name : PARCELABLES) {
            parcelable(name);
        }
        return sLines;
    }

    private static void interfaceScenarios(String name, Class<?> implementation, int count)
            throws Exception {
        Class<?> api = Class.forName(name);
        Class<?> stub = Class.forName(name + "$Stub");
        Wire wire = new Wire();
        Object proxy = stub.getMethod("asInterface", IBinder.class).invoke(null, wire.binder());
        Object local = implementation.getDeclaredConstructor().newInstance();
        emit(name + ".descriptor", ((IBinder) local).getInterfaceDescriptor());
        Method[] methods = api.getDeclaredMethods();
        Arrays.sort(methods, Comparator.comparing(Method::toGenericString));
        int seen = 0;
        for (Method method : methods) {
            if (Modifier.isStatic(method.getModifiers())) continue;
            seen++;
            Class<?>[] types = method.getParameterTypes();
            Object[] values = new Object[types.length];
            for (int i = 0; i < types.length; ++i) values[i] = argument(types[i], i);
            String key = name + "." + method.getName() + "/" + types.length;
            String result;
            try {
                result = describe(method.invoke(proxy, values));
            } catch (InvocationTargetException e) {
                result = "exception:" + e.getCause().getClass().getName();
            }
            emit(key + ".proxy", wire.code + "/" + wire.flags + "/" + wire.data + "/" + result);
            Parcel data = Parcel.obtain();
            data.unmarshall(wire.raw, 0, wire.raw.length);
            data.setDataPosition(0);
            Parcel reply = Parcel.obtain();
            sRecorded = null;
            String handled;
            try {
                Method onTransact = stub.getMethod("onTransact", int.class, Parcel.class, Parcel.class,
                        int.class);
                handled = String.valueOf(onTransact.invoke(local, wire.code, data, reply, wire.flags));
            } catch (InvocationTargetException e) {
                handled = "exception:" + e.getCause().getClass().getName();
            }
            emit(key + ".stub", handled + "/" + sRecorded + "/" + hex(reply));
            data.recycle();
            reply.recycle();
        }
        if (seen != count) throw new AssertionError("Unexpected method count for " + name);
    }

    private static Object unsafeAllocate(Class<?> type) throws Exception {
        Class<?> unsafeType = Class.forName("sun.misc.Unsafe");
        Field field;
        try {
            field = unsafeType.getDeclaredField("THE_ONE");
        } catch (NoSuchFieldException e) {
            field = unsafeType.getDeclaredField("theUnsafe");
        }
        field.setAccessible(true);
        Object unsafe = field.get(null);
        return unsafeType.getMethod("allocateInstance", Class.class).invoke(unsafe, type);
    }

    /** Fill every instance field deterministically, then marshal, unmarshal and marshal again. */
    private static void parcelable(String name) throws Exception {
        Class<?> type = Class.forName(name);
        Object value = unsafeAllocate(type);
        int index = 0;
        for (Class<?> c = type; c != null && c != Object.class; c = c.getSuperclass()) {
            Field[] fields = c.getDeclaredFields();
            Arrays.sort(fields, Comparator.comparing(Field::getName));
            for (Field field : fields) {
                if (Modifier.isStatic(field.getModifiers())) continue;
                field.setAccessible(true);
                Class<?> t = field.getType();
                index++;
                if (t == int.class) field.setInt(value, index * 7);
                else if (t == long.class) field.setLong(value, index * 1000003L);
                else if (t == boolean.class) field.setBoolean(value, index % 2 == 1);
                else if (t == float.class) field.setFloat(value, index + 0.25f);
                else if (t == double.class) field.setDouble(value, index + 0.5d);
                else if (t == byte.class) field.setByte(value, (byte) index);
                else if (t == short.class) field.setShort(value, (short) index);
                else if (t == String.class) field.set(value, field.getName() + index);
            }
        }
        Parcel first = Parcel.obtain();
        ((Parcelable) value).writeToParcel(first, 0);
        String bytes = hex(first);
        first.setDataPosition(0);
        Parcelable.Creator<?> creator = (Parcelable.Creator<?>) type.getField("CREATOR").get(null);
        Object copy = creator.createFromParcel(first);
        Parcel second = Parcel.obtain();
        ((Parcelable) copy).writeToParcel(second, 0);
        emit(name + ".write", bytes);
        emit(name + ".roundtrip", hex(second).equals(bytes) + "/" + first.dataAvail());
        first.recycle();
        second.recycle();
    }

    private static final String[] PARCELABLES = {};

    private static final Object[][] REGISTRY = {
        {"android.media.IAudioService", ImplIAudioService.class, 131},
        {"android.media.INativeSpatializerCallback", ImplINativeSpatializerCallback.class, 2},
        {"android.media.ISpatializer", ImplISpatializer.class, 25},
        {"android.media.ISpatializerCallback", ImplISpatializerCallback.class, 2},
        {"android.media.ISpatializerHeadToSoundStagePoseCallback", ImplISpatializerHeadToSoundStagePoseCallback.class, 1},
        {"android.media.ISpatializerHeadTrackerAvailableCallback", ImplISpatializerHeadTrackerAvailableCallback.class, 1},
        {"android.media.ISpatializerHeadTrackingCallback", ImplISpatializerHeadTrackingCallback.class, 2},
        {"android.media.ISpatializerHeadTrackingModeCallback", ImplISpatializerHeadTrackingModeCallback.class, 2},
        {"android.media.ISpatializerOutputCallback", ImplISpatializerOutputCallback.class, 1},
        {"android.media.SpatializationLevel", ImplSpatializationLevel.class, 0},
        {"android.media.SpatializationMode", ImplSpatializationMode.class, 0},
        {"android.media.SpatializerHeadTrackingMode", ImplSpatializerHeadTrackingMode.class, 0},
    };

    static final class ImplIAudioService extends android.media.IAudioService.Stub {
        @Override
        public int trackPlayer(android.media.PlayerBase.PlayerIdCard a0) {
            record("trackPlayer", new Object[] {a0});
            return 0;
        }
        @Override
        public void playerAttributes(int a0, android.media.AudioAttributes a1) {
            record("playerAttributes", new Object[] {a0, a1});
        }
        @Override
        public void playerEvent(int a0, int a1) {
            record("playerEvent", new Object[] {a0, a1});
        }
        @Override
        public void releasePlayer(int a0) {
            record("releasePlayer", new Object[] {a0});
        }
        @Override
        public int trackRecorder(android.os.IBinder a0) {
            record("trackRecorder", new Object[] {a0});
            return 0;
        }
        @Override
        public void recorderEvent(int a0, int a1) {
            record("recorderEvent", new Object[] {a0, a1});
        }
        @Override
        public void releaseRecorder(int a0) {
            record("releaseRecorder", new Object[] {a0});
        }
        @Override
        public void adjustSuggestedStreamVolume(int a0, int a1, int a2, java.lang.String a3, java.lang.String a4) {
            record("adjustSuggestedStreamVolume", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void adjustStreamVolume(int a0, int a1, int a2, java.lang.String a3) {
            record("adjustStreamVolume", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public void setStreamVolume(int a0, int a1, int a2, java.lang.String a3) {
            record("setStreamVolume", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public boolean isStreamMute(int a0) {
            record("isStreamMute", new Object[] {a0});
            return false;
        }
        @Override
        public void forceRemoteSubmixFullVolume(boolean a0, android.os.IBinder a1) {
            record("forceRemoteSubmixFullVolume", new Object[] {a0, a1});
        }
        @Override
        public boolean isMasterMute() {
            record("isMasterMute", new Object[] {});
            return false;
        }
        @Override
        public void setMasterMute(boolean a0, int a1, java.lang.String a2, int a3) {
            record("setMasterMute", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public int getStreamVolume(int a0) {
            record("getStreamVolume", new Object[] {a0});
            return 0;
        }
        @Override
        public int getStreamMinVolume(int a0) {
            record("getStreamMinVolume", new Object[] {a0});
            return 0;
        }
        @Override
        public int getStreamMaxVolume(int a0) {
            record("getStreamMaxVolume", new Object[] {a0});
            return 0;
        }
        @Override
        public java.util.List getAudioVolumeGroups() {
            record("getAudioVolumeGroups", new Object[] {});
            return null;
        }
        @Override
        public void setVolumeIndexForAttributes(android.media.AudioAttributes a0, int a1, int a2, java.lang.String a3) {
            record("setVolumeIndexForAttributes", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public int getVolumeIndexForAttributes(android.media.AudioAttributes a0) {
            record("getVolumeIndexForAttributes", new Object[] {a0});
            return 0;
        }
        @Override
        public int getMaxVolumeIndexForAttributes(android.media.AudioAttributes a0) {
            record("getMaxVolumeIndexForAttributes", new Object[] {a0});
            return 0;
        }
        @Override
        public int getMinVolumeIndexForAttributes(android.media.AudioAttributes a0) {
            record("getMinVolumeIndexForAttributes", new Object[] {a0});
            return 0;
        }
        @Override
        public int getLastAudibleStreamVolume(int a0) {
            record("getLastAudibleStreamVolume", new Object[] {a0});
            return 0;
        }
        @Override
        public java.util.List getAudioProductStrategies() {
            record("getAudioProductStrategies", new Object[] {});
            return null;
        }
        @Override
        public void setMicrophoneMute(boolean a0, java.lang.String a1, int a2) {
            record("setMicrophoneMute", new Object[] {a0, a1, a2});
        }
        @Override
        public void setRingerModeExternal(int a0, java.lang.String a1) {
            record("setRingerModeExternal", new Object[] {a0, a1});
        }
        @Override
        public void setRingerModeInternal(int a0, java.lang.String a1) {
            record("setRingerModeInternal", new Object[] {a0, a1});
        }
        @Override
        public int getRingerModeExternal() {
            record("getRingerModeExternal", new Object[] {});
            return 0;
        }
        @Override
        public int getRingerModeInternal() {
            record("getRingerModeInternal", new Object[] {});
            return 0;
        }
        @Override
        public boolean isValidRingerMode(int a0) {
            record("isValidRingerMode", new Object[] {a0});
            return false;
        }
        @Override
        public void setVibrateSetting(int a0, int a1) {
            record("setVibrateSetting", new Object[] {a0, a1});
        }
        @Override
        public int getVibrateSetting(int a0) {
            record("getVibrateSetting", new Object[] {a0});
            return 0;
        }
        @Override
        public boolean shouldVibrate(int a0) {
            record("shouldVibrate", new Object[] {a0});
            return false;
        }
        @Override
        public void setMode(int a0, android.os.IBinder a1, java.lang.String a2) {
            record("setMode", new Object[] {a0, a1, a2});
        }
        @Override
        public int getMode() {
            record("getMode", new Object[] {});
            return 0;
        }
        @Override
        public void playSoundEffect(int a0) {
            record("playSoundEffect", new Object[] {a0});
        }
        @Override
        public void playSoundEffectVolume(int a0, float a1) {
            record("playSoundEffectVolume", new Object[] {a0, a1});
        }
        @Override
        public boolean loadSoundEffects() {
            record("loadSoundEffects", new Object[] {});
            return false;
        }
        @Override
        public void unloadSoundEffects() {
            record("unloadSoundEffects", new Object[] {});
        }
        @Override
        public void reloadAudioSettings() {
            record("reloadAudioSettings", new Object[] {});
        }
        @Override
        public void avrcpSupportsAbsoluteVolume(java.lang.String a0, boolean a1) {
            record("avrcpSupportsAbsoluteVolume", new Object[] {a0, a1});
        }
        @Override
        public void setSpeakerphoneOn(boolean a0) {
            record("setSpeakerphoneOn", new Object[] {a0});
        }
        @Override
        public boolean isSpeakerphoneOn() {
            record("isSpeakerphoneOn", new Object[] {});
            return false;
        }
        @Override
        public void setBluetoothScoOn(boolean a0) {
            record("setBluetoothScoOn", new Object[] {a0});
        }
        @Override
        public boolean isBluetoothScoOn() {
            record("isBluetoothScoOn", new Object[] {});
            return false;
        }
        @Override
        public void setBluetoothA2dpOn(boolean a0) {
            record("setBluetoothA2dpOn", new Object[] {a0});
        }
        @Override
        public boolean isBluetoothA2dpOn() {
            record("isBluetoothA2dpOn", new Object[] {});
            return false;
        }
        @Override
        public int requestAudioFocus(android.media.AudioAttributes a0, int a1, android.os.IBinder a2, android.media.IAudioFocusDispatcher a3, java.lang.String a4, java.lang.String a5, int a6, android.media.audiopolicy.IAudioPolicyCallback a7, int a8) {
            record("requestAudioFocus", new Object[] {a0, a1, a2, a3, a4, a5, a6, a7, a8});
            return 0;
        }
        @Override
        public int abandonAudioFocus(android.media.IAudioFocusDispatcher a0, java.lang.String a1, android.media.AudioAttributes a2, java.lang.String a3) {
            record("abandonAudioFocus", new Object[] {a0, a1, a2, a3});
            return 0;
        }
        @Override
        public void unregisterAudioFocusClient(java.lang.String a0) {
            record("unregisterAudioFocusClient", new Object[] {a0});
        }
        @Override
        public int getCurrentAudioFocus() {
            record("getCurrentAudioFocus", new Object[] {});
            return 0;
        }
        @Override
        public void startBluetoothSco(android.os.IBinder a0, int a1) {
            record("startBluetoothSco", new Object[] {a0, a1});
        }
        @Override
        public void startBluetoothScoVirtualCall(android.os.IBinder a0) {
            record("startBluetoothScoVirtualCall", new Object[] {a0});
        }
        @Override
        public void stopBluetoothSco(android.os.IBinder a0) {
            record("stopBluetoothSco", new Object[] {a0});
        }
        @Override
        public void forceVolumeControlStream(int a0, android.os.IBinder a1) {
            record("forceVolumeControlStream", new Object[] {a0, a1});
        }
        @Override
        public void setRingtonePlayer(android.media.IRingtonePlayer a0) {
            record("setRingtonePlayer", new Object[] {a0});
        }
        @Override
        public android.media.IRingtonePlayer getRingtonePlayer() {
            record("getRingtonePlayer", new Object[] {});
            return null;
        }
        @Override
        public int getUiSoundsStreamType() {
            record("getUiSoundsStreamType", new Object[] {});
            return 0;
        }
        @Override
        public void setWiredDeviceConnectionState(int a0, int a1, java.lang.String a2, java.lang.String a3, java.lang.String a4) {
            record("setWiredDeviceConnectionState", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void handleBluetoothA2dpDeviceConfigChange(android.bluetooth.BluetoothDevice a0) {
            record("handleBluetoothA2dpDeviceConfigChange", new Object[] {a0});
        }
        @Override
        public void handleBluetoothA2dpActiveDeviceChange(android.bluetooth.BluetoothDevice a0, int a1, int a2, boolean a3, int a4) {
            record("handleBluetoothA2dpActiveDeviceChange", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public android.media.AudioRoutesInfo startWatchingRoutes(android.media.IAudioRoutesObserver a0) {
            record("startWatchingRoutes", new Object[] {a0});
            return null;
        }
        @Override
        public boolean isCameraSoundForced() {
            record("isCameraSoundForced", new Object[] {});
            return false;
        }
        @Override
        public void setVolumeController(android.media.IVolumeController a0) {
            record("setVolumeController", new Object[] {a0});
        }
        @Override
        public void notifyVolumeControllerVisible(android.media.IVolumeController a0, boolean a1) {
            record("notifyVolumeControllerVisible", new Object[] {a0, a1});
        }
        @Override
        public boolean isStreamAffectedByRingerMode(int a0) {
            record("isStreamAffectedByRingerMode", new Object[] {a0});
            return false;
        }
        @Override
        public boolean isStreamAffectedByMute(int a0) {
            record("isStreamAffectedByMute", new Object[] {a0});
            return false;
        }
        @Override
        public void disableSafeMediaVolume(java.lang.String a0) {
            record("disableSafeMediaVolume", new Object[] {a0});
        }
        @Override
        public int setHdmiSystemAudioSupported(boolean a0) {
            record("setHdmiSystemAudioSupported", new Object[] {a0});
            return 0;
        }
        @Override
        public boolean isHdmiSystemAudioSupported() {
            record("isHdmiSystemAudioSupported", new Object[] {});
            return false;
        }
        @Override
        public java.lang.String registerAudioPolicy(android.media.audiopolicy.AudioPolicyConfig a0, android.media.audiopolicy.IAudioPolicyCallback a1, boolean a2, boolean a3, boolean a4, boolean a5, android.media.projection.IMediaProjection a6) {
            record("registerAudioPolicy", new Object[] {a0, a1, a2, a3, a4, a5, a6});
            return null;
        }
        @Override
        public void unregisterAudioPolicyAsync(android.media.audiopolicy.IAudioPolicyCallback a0) {
            record("unregisterAudioPolicyAsync", new Object[] {a0});
        }
        @Override
        public void unregisterAudioPolicy(android.media.audiopolicy.IAudioPolicyCallback a0) {
            record("unregisterAudioPolicy", new Object[] {a0});
        }
        @Override
        public int addMixForPolicy(android.media.audiopolicy.AudioPolicyConfig a0, android.media.audiopolicy.IAudioPolicyCallback a1) {
            record("addMixForPolicy", new Object[] {a0, a1});
            return 0;
        }
        @Override
        public int removeMixForPolicy(android.media.audiopolicy.AudioPolicyConfig a0, android.media.audiopolicy.IAudioPolicyCallback a1) {
            record("removeMixForPolicy", new Object[] {a0, a1});
            return 0;
        }
        @Override
        public int setFocusPropertiesForPolicy(int a0, android.media.audiopolicy.IAudioPolicyCallback a1) {
            record("setFocusPropertiesForPolicy", new Object[] {a0, a1});
            return 0;
        }
        @Override
        public void setVolumePolicy(android.media.VolumePolicy a0) {
            record("setVolumePolicy", new Object[] {a0});
        }
        @Override
        public boolean hasRegisteredDynamicPolicy() {
            record("hasRegisteredDynamicPolicy", new Object[] {});
            return false;
        }
        @Override
        public void registerRecordingCallback(android.media.IRecordingConfigDispatcher a0) {
            record("registerRecordingCallback", new Object[] {a0});
        }
        @Override
        public void unregisterRecordingCallback(android.media.IRecordingConfigDispatcher a0) {
            record("unregisterRecordingCallback", new Object[] {a0});
        }
        @Override
        public java.util.List getActiveRecordingConfigurations() {
            record("getActiveRecordingConfigurations", new Object[] {});
            return null;
        }
        @Override
        public void registerPlaybackCallback(android.media.IPlaybackConfigDispatcher a0) {
            record("registerPlaybackCallback", new Object[] {a0});
        }
        @Override
        public void unregisterPlaybackCallback(android.media.IPlaybackConfigDispatcher a0) {
            record("unregisterPlaybackCallback", new Object[] {a0});
        }
        @Override
        public java.util.List getActivePlaybackConfigurations() {
            record("getActivePlaybackConfigurations", new Object[] {});
            return null;
        }
        @Override
        public void disableRingtoneSync(int a0) {
            record("disableRingtoneSync", new Object[] {a0});
        }
        @Override
        public int getFocusRampTimeMs(int a0, android.media.AudioAttributes a1) {
            record("getFocusRampTimeMs", new Object[] {a0, a1});
            return 0;
        }
        @Override
        public int dispatchFocusChange(android.media.AudioFocusInfo a0, int a1, android.media.audiopolicy.IAudioPolicyCallback a2) {
            record("dispatchFocusChange", new Object[] {a0, a1, a2});
            return 0;
        }
        @Override
        public void playerHasOpPlayAudio(int a0, boolean a1) {
            record("playerHasOpPlayAudio", new Object[] {a0, a1});
        }
        @Override
        public void setBluetoothHearingAidDeviceConnectionState(android.bluetooth.BluetoothDevice a0, int a1, boolean a2, int a3) {
            record("setBluetoothHearingAidDeviceConnectionState", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public void setBluetoothA2dpDeviceConnectionStateSuppressNoisyIntent(android.bluetooth.BluetoothDevice a0, int a1, int a2, boolean a3, int a4) {
            record("setBluetoothA2dpDeviceConnectionStateSuppressNoisyIntent", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void setFocusRequestResultFromExtPolicy(android.media.AudioFocusInfo a0, int a1, android.media.audiopolicy.IAudioPolicyCallback a2) {
            record("setFocusRequestResultFromExtPolicy", new Object[] {a0, a1, a2});
        }
        @Override
        public void registerAudioServerStateDispatcher(android.media.IAudioServerStateDispatcher a0) {
            record("registerAudioServerStateDispatcher", new Object[] {a0});
        }
        @Override
        public void unregisterAudioServerStateDispatcher(android.media.IAudioServerStateDispatcher a0) {
            record("unregisterAudioServerStateDispatcher", new Object[] {a0});
        }
        @Override
        public boolean isAudioServerRunning() {
            record("isAudioServerRunning", new Object[] {});
            return false;
        }
        @Override
        public int setUidDeviceAffinity(android.media.audiopolicy.IAudioPolicyCallback a0, int a1, int[] a2, java.lang.String[] a3) {
            record("setUidDeviceAffinity", new Object[] {a0, a1, a2, a3});
            return 0;
        }
        @Override
        public int removeUidDeviceAffinity(android.media.audiopolicy.IAudioPolicyCallback a0, int a1) {
            record("removeUidDeviceAffinity", new Object[] {a0, a1});
            return 0;
        }
        @Override
        public boolean hasHapticChannels(android.net.Uri a0) {
            record("hasHapticChannels", new Object[] {a0});
            return false;
        }
        @Override
        public int setAllowedCapturePolicy(int a0) {
            record("setAllowedCapturePolicy", new Object[] {a0});
            return 0;
        }
        @Override
        public int getAllowedCapturePolicy() {
            record("getAllowedCapturePolicy", new Object[] {});
            return 0;
        }
        @Override
        public int getSpatializerImmersiveAudioLevel() {
            record("getSpatializerImmersiveAudioLevel", new Object[] {});
            return 0;
        }
        @Override
        public boolean isSpatializerEnabled() {
            record("isSpatializerEnabled", new Object[] {});
            return false;
        }
        @Override
        public boolean isSpatializerAvailable() {
            record("isSpatializerAvailable", new Object[] {});
            return false;
        }
        @Override
        public boolean isSpatializerAvailableForDevice(android.media.AudioDeviceAttributes a0) {
            record("isSpatializerAvailableForDevice", new Object[] {a0});
            return false;
        }
        @Override
        public boolean hasHeadTracker(android.media.AudioDeviceAttributes a0) {
            record("hasHeadTracker", new Object[] {a0});
            return false;
        }
        @Override
        public void setHeadTrackerEnabled(boolean a0, android.media.AudioDeviceAttributes a1) {
            record("setHeadTrackerEnabled", new Object[] {a0, a1});
        }
        @Override
        public boolean isHeadTrackerEnabled(android.media.AudioDeviceAttributes a0) {
            record("isHeadTrackerEnabled", new Object[] {a0});
            return false;
        }
        @Override
        public boolean isHeadTrackerAvailable() {
            record("isHeadTrackerAvailable", new Object[] {});
            return false;
        }
        @Override
        public void registerSpatializerHeadTrackerAvailableCallback(android.media.ISpatializerHeadTrackerAvailableCallback a0, boolean a1) {
            record("registerSpatializerHeadTrackerAvailableCallback", new Object[] {a0, a1});
        }
        @Override
        public void setSpatializerEnabled(boolean a0) {
            record("setSpatializerEnabled", new Object[] {a0});
        }
        @Override
        public boolean canBeSpatialized(android.media.AudioAttributes a0, android.media.AudioFormat a1) {
            record("canBeSpatialized", new Object[] {a0, a1});
            return false;
        }
        @Override
        public void registerSpatializerCallback(android.media.ISpatializerCallback a0) {
            record("registerSpatializerCallback", new Object[] {a0});
        }
        @Override
        public void unregisterSpatializerCallback(android.media.ISpatializerCallback a0) {
            record("unregisterSpatializerCallback", new Object[] {a0});
        }
        @Override
        public void registerSpatializerHeadTrackingCallback(android.media.ISpatializerHeadTrackingModeCallback a0) {
            record("registerSpatializerHeadTrackingCallback", new Object[] {a0});
        }
        @Override
        public void unregisterSpatializerHeadTrackingCallback(android.media.ISpatializerHeadTrackingModeCallback a0) {
            record("unregisterSpatializerHeadTrackingCallback", new Object[] {a0});
        }
        @Override
        public void registerHeadToSoundstagePoseCallback(android.media.ISpatializerHeadToSoundStagePoseCallback a0) {
            record("registerHeadToSoundstagePoseCallback", new Object[] {a0});
        }
        @Override
        public void unregisterHeadToSoundstagePoseCallback(android.media.ISpatializerHeadToSoundStagePoseCallback a0) {
            record("unregisterHeadToSoundstagePoseCallback", new Object[] {a0});
        }
        @Override
        public java.util.List getSpatializerCompatibleAudioDevices() {
            record("getSpatializerCompatibleAudioDevices", new Object[] {});
            return null;
        }
        @Override
        public void addSpatializerCompatibleAudioDevice(android.media.AudioDeviceAttributes a0) {
            record("addSpatializerCompatibleAudioDevice", new Object[] {a0});
        }
        @Override
        public void removeSpatializerCompatibleAudioDevice(android.media.AudioDeviceAttributes a0) {
            record("removeSpatializerCompatibleAudioDevice", new Object[] {a0});
        }
        @Override
        public void setDesiredHeadTrackingMode(int a0) {
            record("setDesiredHeadTrackingMode", new Object[] {a0});
        }
        @Override
        public int getDesiredHeadTrackingMode() {
            record("getDesiredHeadTrackingMode", new Object[] {});
            return 0;
        }
        @Override
        public int[] getSupportedHeadTrackingModes() {
            record("getSupportedHeadTrackingModes", new Object[] {});
            return null;
        }
        @Override
        public int getActualHeadTrackingMode() {
            record("getActualHeadTrackingMode", new Object[] {});
            return 0;
        }
        @Override
        public void setSpatializerGlobalTransform(float[] a0) {
            record("setSpatializerGlobalTransform", new Object[] {a0});
        }
        @Override
        public void recenterHeadTracker() {
            record("recenterHeadTracker", new Object[] {});
        }
        @Override
        public void setSpatializerParameter(int a0, byte[] a1) {
            record("setSpatializerParameter", new Object[] {a0, a1});
        }
        @Override
        public void getSpatializerParameter(int a0, byte[] a1) {
            record("getSpatializerParameter", new Object[] {a0, a1});
        }
        @Override
        public int getSpatializerOutput() {
            record("getSpatializerOutput", new Object[] {});
            return 0;
        }
        @Override
        public void registerSpatializerOutputCallback(android.media.ISpatializerOutputCallback a0) {
            record("registerSpatializerOutputCallback", new Object[] {a0});
        }
        @Override
        public void unregisterSpatializerOutputCallback(android.media.ISpatializerOutputCallback a0) {
            record("unregisterSpatializerOutputCallback", new Object[] {a0});
        }
        @Override
        public int setRecordSilenced(java.lang.String a0, boolean a1) {
            record("setRecordSilenced", new Object[] {a0, a1});
            return 0;
        }
    }

    static final class ImplINativeSpatializerCallback extends android.media.INativeSpatializerCallback.Stub {
        @Override
        public void onLevelChanged(byte a0) {
            record("onLevelChanged", new Object[] {a0});
        }
        @Override
        public void onOutputChanged(int a0) {
            record("onOutputChanged", new Object[] {a0});
        }
    }

    static final class ImplISpatializer extends android.media.ISpatializer.Stub {
        @Override
        public void release() {
            record("release", new Object[] {});
        }
        @Override
        public byte[] getSupportedLevels() {
            record("getSupportedLevels", new Object[] {});
            return null;
        }
        @Override
        public void setLevel(byte a0) {
            record("setLevel", new Object[] {a0});
        }
        @Override
        public byte getLevel() {
            record("getLevel", new Object[] {});
            return (byte) 0;
        }
        @Override
        public boolean isHeadTrackingSupported() {
            record("isHeadTrackingSupported", new Object[] {});
            return false;
        }
        @Override
        public byte[] getSupportedHeadTrackingModes() {
            record("getSupportedHeadTrackingModes", new Object[] {});
            return null;
        }
        @Override
        public void setDesiredHeadTrackingMode(byte a0) {
            record("setDesiredHeadTrackingMode", new Object[] {a0});
        }
        @Override
        public byte getActualHeadTrackingMode() {
            record("getActualHeadTrackingMode", new Object[] {});
            return (byte) 0;
        }
        @Override
        public void recenterHeadTracker() {
            record("recenterHeadTracker", new Object[] {});
        }
        @Override
        public void setGlobalTransform(float[] a0) {
            record("setGlobalTransform", new Object[] {a0});
        }
        @Override
        public void setHeadSensor(int a0) {
            record("setHeadSensor", new Object[] {a0});
        }
        @Override
        public void setScreenSensor(int a0) {
            record("setScreenSensor", new Object[] {a0});
        }
        @Override
        public void setDisplayOrientation(float a0) {
            record("setDisplayOrientation", new Object[] {a0});
        }
        @Override
        public void setHingeAngle(float a0) {
            record("setHingeAngle", new Object[] {a0});
        }
        @Override
        public byte[] getSupportedModes() {
            record("getSupportedModes", new Object[] {});
            return null;
        }
        @Override
        public void registerHeadTrackingCallback(android.media.ISpatializerHeadTrackingCallback a0) {
            record("registerHeadTrackingCallback", new Object[] {a0});
        }
        @Override
        public void setParameter(int a0, byte[] a1) {
            record("setParameter", new Object[] {a0, a1});
        }
        @Override
        public void getParameter(int a0, byte[] a1) {
            record("getParameter", new Object[] {a0, a1});
        }
        @Override
        public int getOutput() {
            record("getOutput", new Object[] {});
            return 0;
        }
        @Override
        public void releasePlayer(long a0) {
            record("releasePlayer", new Object[] {a0});
        }
        @Override
        public void setPlayerSessionId(long a0, int a1) {
            record("setPlayerSessionId", new Object[] {a0, a1});
        }
        @Override
        public int enableSpatialization(long a0, boolean a1) {
            record("enableSpatialization", new Object[] {a0, a1});
            return 0;
        }
        @Override
        public int isSpatializationEnabled(long a0) {
            record("isSpatializationEnabled", new Object[] {a0});
            return 0;
        }
        @Override
        public int setAudioOrientation(long a0, float a1, float a2, float a3, float a4) {
            record("setAudioOrientation", new Object[] {a0, a1, a2, a3, a4});
            return 0;
        }
        @Override
        public int setAudioPose(long a0, float a1, float a2, float a3, float a4, float a5, float a6, float a7) {
            record("setAudioPose", new Object[] {a0, a1, a2, a3, a4, a5, a6, a7});
            return 0;
        }
    }

    static final class ImplISpatializerCallback extends android.media.ISpatializerCallback.Stub {
        @Override
        public void dispatchSpatializerEnabledChanged(boolean a0) {
            record("dispatchSpatializerEnabledChanged", new Object[] {a0});
        }
        @Override
        public void dispatchSpatializerAvailableChanged(boolean a0) {
            record("dispatchSpatializerAvailableChanged", new Object[] {a0});
        }
    }

    static final class ImplISpatializerHeadToSoundStagePoseCallback extends android.media.ISpatializerHeadToSoundStagePoseCallback.Stub {
        @Override
        public void dispatchPoseChanged(float[] a0) {
            record("dispatchPoseChanged", new Object[] {a0});
        }
    }

    static final class ImplISpatializerHeadTrackerAvailableCallback extends android.media.ISpatializerHeadTrackerAvailableCallback.Stub {
        @Override
        public void dispatchSpatializerHeadTrackerAvailable(boolean a0) {
            record("dispatchSpatializerHeadTrackerAvailable", new Object[] {a0});
        }
    }

    static final class ImplISpatializerHeadTrackingCallback extends android.media.ISpatializerHeadTrackingCallback.Stub {
        @Override
        public void onHeadTrackingModeChanged(byte a0) {
            record("onHeadTrackingModeChanged", new Object[] {a0});
        }
        @Override
        public void onHeadToSoundStagePoseUpdated(float[] a0) {
            record("onHeadToSoundStagePoseUpdated", new Object[] {a0});
        }
    }

    static final class ImplISpatializerHeadTrackingModeCallback extends android.media.ISpatializerHeadTrackingModeCallback.Stub {
        @Override
        public void dispatchSpatializerActualHeadTrackingModeChanged(int a0) {
            record("dispatchSpatializerActualHeadTrackingModeChanged", new Object[] {a0});
        }
        @Override
        public void dispatchSpatializerDesiredHeadTrackingModeChanged(int a0) {
            record("dispatchSpatializerDesiredHeadTrackingModeChanged", new Object[] {a0});
        }
    }

    static final class ImplISpatializerOutputCallback extends android.media.ISpatializerOutputCallback.Stub {
        @Override
        public void dispatchSpatializerOutputChanged(int a0) {
            record("dispatchSpatializerOutputChanged", new Object[] {a0});
        }
    }

    static final class ImplSpatializationLevel extends android.media.SpatializationLevel.Stub {
    }

    static final class ImplSpatializationMode extends android.media.SpatializationMode.Stub {
    }

    static final class ImplSpatializerHeadTrackingMode extends android.media.SpatializerHeadTrackingMode.Stub {
    }
}
