// Copyright 2026 Picomisu contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by tools/generate-pico-api-fixture.py; do not edit.
package org.picomisu.runtime;

import android.content.ComponentName;
import android.os.Bundle;
import android.os.IBinder;
import android.os.Parcel;
import android.os.Parcelable;

import java.io.PrintStream;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Proxy;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * Wire-format scenarios for the PICO framework AIDL interfaces and parcelables. The same
 * probe JAR runs on the factory and the Source framework; lines "factory-only-aidl key=value" are
 * compared by tools/compare-pico-api-runtime.py.
 */
public final class FactoryOnlyAidlFixture {
    static final int EXPECTED_LINES = 332;
    private static PrintStream sOut;
    private static int sLines;
    private static String sRecorded;

    private FactoryOnlyAidlFixture() {}

    public static void main(String[] args) throws Exception {
        System.out.println("factory-only-aidl-fixture lines=" + run(System.out));
    }

    static void emit(String key, Object value) {
        sOut.println("factory-only-aidl " + key + "=" + value);
        sLines++;
    }

    static void record(String name, Object[] args) {
        sRecorded = name + describe(args);
    }

    private static final char[] DIGITS = "0123456789abcdef".toCharArray();

    static String hex(Parcel parcel) {
        byte[] bytes = parcel.marshall();
        char[] text = new char[bytes.length * 2];
        for (int i = 0; i < bytes.length; ++i) {
            text[2 * i] = DIGITS[(bytes[i] >> 4) & 0xf];
            text[2 * i + 1] = DIGITS[bytes[i] & 0xf];
        }
        return new String(text);
    }

    static String describe(Object value) {
        if (value == null) return "null";
        if (value instanceof Object[]) {
            StringBuilder text = new StringBuilder("[");
            for (Object item : (Object[]) value) text.append(describe(item)).append(',');
            return text.append(']').toString();
        }
        if (value instanceof int[]) return Arrays.toString((int[]) value);
        if (value instanceof long[]) return Arrays.toString((long[]) value);
        if (value instanceof byte[]) return Arrays.toString((byte[]) value);
        if (value instanceof boolean[]) return Arrays.toString((boolean[]) value);
        if (value instanceof float[]) return Arrays.toString((float[]) value);
        if (value instanceof Bundle) {
            Bundle bundle = (Bundle) value;
            List<String> keys = new ArrayList<>(bundle.keySet());
            keys.sort(null);
            StringBuilder text = new StringBuilder("Bundle{");
            for (String key : keys) text.append(key).append('=').append(bundle.get(key)).append(';');
            return text.append('}').toString();
        }
        if (value instanceof Parcelable) {
            Parcel parcel = Parcel.obtain();
            ((Parcelable) value).writeToParcel(parcel, 0);
            String result = value.getClass().getName() + ":" + hex(parcel);
            parcel.recycle();
            return result;
        }
        return String.valueOf(value);
    }

    static Object argument(Class<?> type, int index) {
        if (type == int.class) return 0x11223340 + index;
        if (type == long.class) return 0x1122334455667700L + index;
        if (type == boolean.class) return index % 2 == 0;
        if (type == byte.class) return (byte) (0x40 + index);
        if (type == char.class) return (char) ('A' + index);
        if (type == short.class) return (short) (0x30 + index);
        if (type == float.class) return 1.5f + index;
        if (type == double.class) return 2.5d + index;
        if (type == String.class) return "s" + index;
        if (type == String[].class) return new String[] {"a" + index, "b" + index};
        if (type == int[].class) return new int[] {index, index + 1};
        if (type == Bundle.class) {
            Bundle bundle = new Bundle();
            bundle.putString("k" + index, "v" + index);
            return bundle;
        }
        if (type == ComponentName.class) return new ComponentName("org.picomisu", "org.picomisu.C" + index);
        if (type == byte[].class) return new byte[] {(byte) index, (byte) 0x5a};
        // Out arrays must be non-null: Parcel.readXxxArray(null) aborts in native code.
        if (type.isArray()) return java.lang.reflect.Array.newInstance(type.getComponentType(), 2);
        return null;
    }

    /** IBinder that records transactions and answers with an empty no-exception reply. */
    static final class Wire {
        int code;
        int flags;
        String data;
        byte[] raw;

        IBinder binder() {
            return (IBinder) Proxy.newProxyInstance(IBinder.class.getClassLoader(),
                    new Class<?>[] {IBinder.class}, (proxy, method, values) -> {
                        switch (method.getName()) {
                            case "transact": {
                                code = (Integer) values[0];
                                flags = (Integer) values[3];
                                Parcel in = (Parcel) values[1];
                                raw = in.marshall();
                                data = hex(in);
                                Parcel reply = (Parcel) values[2];
                                if (reply != null) {
                                    reply.writeNoException();
                                    for (int i = 0; i < 16; ++i) reply.writeInt(0);
                                    reply.setDataPosition(0);
                                }
                                return true;
                            }
                            case "queryLocalInterface": return null;
                            case "isBinderAlive": case "pingBinder": return true;
                            case "linkToDeath": return null;
                            case "unlinkToDeath": return true;
                            case "getInterfaceDescriptor": return "wire";
                            default: return null;
                        }
                    });
        }
    }

    static int run(PrintStream out) throws Exception {
        sOut = out;
        sLines = 0;
        for (Object[] entry : REGISTRY) {
            interfaceScenarios((String) entry[0], (Class<?>) entry[1], (Integer) entry[2]);
        }
        for (String name : PARCELABLES) {
            parcelable(name);
        }
        return sLines;
    }

    private static void interfaceScenarios(String name, Class<?> implementation, int count)
            throws Exception {
        Class<?> api = Class.forName(name);
        Class<?> stub = Class.forName(name + "$Stub");
        Wire wire = new Wire();
        Object proxy = stub.getMethod("asInterface", IBinder.class).invoke(null, wire.binder());
        Object local = implementation.getDeclaredConstructor().newInstance();
        emit(name + ".descriptor", ((IBinder) local).getInterfaceDescriptor());
        Method[] methods = api.getDeclaredMethods();
        Arrays.sort(methods, Comparator.comparing(Method::toGenericString));
        int seen = 0;
        for (Method method : methods) {
            if (Modifier.isStatic(method.getModifiers())) continue;
            seen++;
            Class<?>[] types = method.getParameterTypes();
            Object[] values = new Object[types.length];
            for (int i = 0; i < types.length; ++i) values[i] = argument(types[i], i);
            String key = name + "." + method.getName() + "/" + types.length;
            String result;
            try {
                result = describe(method.invoke(proxy, values));
            } catch (InvocationTargetException e) {
                result = "exception:" + e.getCause().getClass().getName();
            }
            emit(key + ".proxy", wire.code + "/" + wire.flags + "/" + wire.data + "/" + result);
            Parcel data = Parcel.obtain();
            data.unmarshall(wire.raw, 0, wire.raw.length);
            data.setDataPosition(0);
            Parcel reply = Parcel.obtain();
            sRecorded = null;
            String handled;
            try {
                Method onTransact = stub.getMethod("onTransact", int.class, Parcel.class, Parcel.class,
                        int.class);
                handled = String.valueOf(onTransact.invoke(local, wire.code, data, reply, wire.flags));
            } catch (InvocationTargetException e) {
                handled = "exception:" + e.getCause().getClass().getName();
            }
            emit(key + ".stub", handled + "/" + sRecorded + "/" + hex(reply));
            data.recycle();
            reply.recycle();
        }
        if (seen != count) throw new AssertionError("Unexpected method count for " + name);
    }

    private static Object unsafeAllocate(Class<?> type) throws Exception {
        Class<?> unsafeType = Class.forName("sun.misc.Unsafe");
        Field field;
        try {
            field = unsafeType.getDeclaredField("THE_ONE");
        } catch (NoSuchFieldException e) {
            field = unsafeType.getDeclaredField("theUnsafe");
        }
        field.setAccessible(true);
        Object unsafe = field.get(null);
        return unsafeType.getMethod("allocateInstance", Class.class).invoke(unsafe, type);
    }

    /** Fill every instance field deterministically, then marshal, unmarshal and marshal again. */
    private static void parcelable(String name) throws Exception {
        Class<?> type = Class.forName(name);
        Object value = unsafeAllocate(type);
        int index = 0;
        for (Class<?> c = type; c != null && c != Object.class; c = c.getSuperclass()) {
            Field[] fields = c.getDeclaredFields();
            Arrays.sort(fields, Comparator.comparing(Field::getName));
            for (Field field : fields) {
                if (Modifier.isStatic(field.getModifiers())) continue;
                field.setAccessible(true);
                Class<?> t = field.getType();
                index++;
                if (t == int.class) field.setInt(value, index * 7);
                else if (t == long.class) field.setLong(value, index * 1000003L);
                else if (t == boolean.class) field.setBoolean(value, index % 2 == 1);
                else if (t == float.class) field.setFloat(value, index + 0.25f);
                else if (t == double.class) field.setDouble(value, index + 0.5d);
                else if (t == byte.class) field.setByte(value, (byte) index);
                else if (t == short.class) field.setShort(value, (short) index);
                else if (t == String.class) field.set(value, field.getName() + index);
            }
        }
        Parcel first = Parcel.obtain();
        ((Parcelable) value).writeToParcel(first, 0);
        String bytes = hex(first);
        first.setDataPosition(0);
        Parcelable.Creator<?> creator = (Parcelable.Creator<?>) type.getField("CREATOR").get(null);
        Object copy = creator.createFromParcel(first);
        Parcel second = Parcel.obtain();
        ((Parcelable) copy).writeToParcel(second, 0);
        emit(name + ".write", bytes);
        emit(name + ".roundtrip", hex(second).equals(bytes) + "/" + first.dataAvail());
        first.recycle();
        second.recycle();
    }

    private static final String[] PARCELABLES = {"android.app.SceneData", "android.app.PrefetchInfo"};

    private static final Object[][] REGISTRY = {
        {"android.app.IBackupAgent", ImplIBackupAgent.class, 8},
        {"android.app.IDataListener", ImplIDataListener.class, 2},
        {"android.app.IFreezeManager", ImplIFreezeManager.class, 3},
        {"android.app.IPrefetchCallback", ImplIPrefetchCallback.class, 1},
        {"android.app.IPrefetchManager", ImplIPrefetchManager.class, 4},
        {"android.app.IPrefetchObserver", ImplIPrefetchObserver.class, 1},
        {"android.app.ISceneInfoManager", ImplISceneInfoManager.class, 6},
        {"android.app.IUnFreezeCallback", ImplIUnFreezeCallback.class, 1},
        {"android.bluetooth.IBluetoothPan", ImplIBluetoothPan.class, 7},
        {"android.content.pm.IPackageManagerMonitorEx", ImplIPackageManagerMonitorEx.class, 0},
        {"android.dvr.IVirtualInputService", ImplIVirtualInputService.class, 14},
        {"android.net.INetworkStatsService", ImplINetworkStatsService.class, 13},
        {"android.os.IDeviceIdleControllerSmtEx", ImplIDeviceIdleControllerSmtEx.class, 1},
        {"android.os.IPowerAdvisor", ImplIPowerAdvisor.class, 15},
        {"android.os.IStatsManager", ImplIStatsManager.class, 25},
        {"android.os.IVibratorService", ImplIVibratorService.class, 4},
        {"android.pc.ISmtPCManager", ImplISmtPCManager.class, 1},
        {"android.view.ISystemGestureExclusionListener", ImplISystemGestureExclusionListener.class, 1},
        {"com.android.internal.app.ISysTransServer", ImplISysTransServer.class, 6},
        {"com.android.internal.app.ITransferServer", ImplITransferServer.class, 31},
        {"com.android.internal.car.ICarStatsService", ImplICarStatsService.class, 1},
        {"com.android.internal.policy.IKeyguardFaceIDVerifyCallback", ImplIKeyguardFaceIDVerifyCallback.class, 1},
        {"com.android.internal.policy.IKeyguardFingerprintVerifyCallback", ImplIKeyguardFingerprintVerifyCallback.class, 5},
        {"com.android.internal.policy.IKeyguardVerifyCallback", ImplIKeyguardVerifyCallback.class, 1},
    };

    static final class ImplIBackupAgent extends android.app.IBackupAgent.Stub {
        @Override
        public void doBackup(android.os.ParcelFileDescriptor a0, android.os.ParcelFileDescriptor a1, android.os.ParcelFileDescriptor a2, long a3, android.app.backup.IBackupCallback a4, int a5) {
            record("doBackup", new Object[] {a0, a1, a2, a3, a4, a5});
        }
        @Override
        public void doRestore(android.os.ParcelFileDescriptor a0, long a1, android.os.ParcelFileDescriptor a2, int a3, android.app.backup.IBackupManager a4) {
            record("doRestore", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void doFullBackup(android.os.ParcelFileDescriptor a0, long a1, int a2, android.app.backup.IBackupManager a3, int a4, java.util.List a5, java.util.List a6) {
            record("doFullBackup", new Object[] {a0, a1, a2, a3, a4, a5, a6});
        }
        @Override
        public void doMeasureFullBackup(long a0, int a1, android.app.backup.IBackupManager a2, int a3) {
            record("doMeasureFullBackup", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public void doQuotaExceeded(long a0, long a1, android.app.backup.IBackupCallback a2) {
            record("doQuotaExceeded", new Object[] {a0, a1, a2});
        }
        @Override
        public void doRestoreFile(android.os.ParcelFileDescriptor a0, long a1, int a2, java.lang.String a3, java.lang.String a4, long a5, long a6, int a7, android.app.backup.IBackupManager a8) {
            record("doRestoreFile", new Object[] {a0, a1, a2, a3, a4, a5, a6, a7, a8});
        }
        @Override
        public void doRestoreFinished(int a0, android.app.backup.IBackupManager a1) {
            record("doRestoreFinished", new Object[] {a0, a1});
        }
        @Override
        public void fail(java.lang.String a0) {
            record("fail", new Object[] {a0});
        }
    }

    static final class ImplIDataListener extends android.app.IDataListener.Stub {
        @Override
        public void onInfoChange(int a0, int a1, android.app.SceneData a2) {
            record("onInfoChange", new Object[] {a0, a1, a2});
        }
        @Override
        public void onServerDied() {
            record("onServerDied", new Object[] {});
        }
    }

    static final class ImplIFreezeManager extends android.app.IFreezeManager.Stub {
        @Override
        public void registerUnFreezeListener(int a0, android.app.IUnFreezeCallback a1, boolean a2) {
            record("registerUnFreezeListener", new Object[] {a0, a1, a2});
        }
        @Override
        public void unRegisterUnFreezeListener(int a0, android.app.IUnFreezeCallback a1) {
            record("unRegisterUnFreezeListener", new Object[] {a0, a1});
        }
        @Override
        public void freezeUid(int a0) {
            record("freezeUid", new Object[] {a0});
        }
    }

    static final class ImplIPrefetchCallback extends android.app.IPrefetchCallback.Stub {
        @Override
        public void onRealStart(int a0) {
            record("onRealStart", new Object[] {a0});
        }
    }

    static final class ImplIPrefetchManager extends android.app.IPrefetchManager.Stub {
        @Override
        public void registerStartPrefetchListener(android.app.IPrefetchCallback a0) {
            record("registerStartPrefetchListener", new Object[] {a0});
        }
        @Override
        public void registerPrefetchObserver(android.app.IPrefetchObserver a0) {
            record("registerPrefetchObserver", new Object[] {a0});
        }
        @Override
        public void unregisterPrefetchObserver(android.app.IPrefetchObserver a0) {
            record("unregisterPrefetchObserver", new Object[] {a0});
        }
        @Override
        public boolean isPrefetch(java.lang.String a0) {
            record("isPrefetch", new Object[] {a0});
            return false;
        }
    }

    static final class ImplIPrefetchObserver extends android.app.IPrefetchObserver.Stub {
        @Override
        public void onPrefetchKilled(android.app.PrefetchInfo a0) {
            record("onPrefetchKilled", new Object[] {a0});
        }
    }

    static final class ImplISceneInfoManager extends android.app.ISceneInfoManager.Stub {
        @Override
        public boolean reportData(int a0, int a1) {
            record("reportData", new Object[] {a0, a1});
            return false;
        }
        @Override
        public boolean reportDataInfo(int a0, int a1, android.app.SceneData a2) {
            record("reportDataInfo", new Object[] {a0, a1, a2});
            return false;
        }
        @Override
        public boolean registerListener(int a0, android.app.IDataListener a1, java.lang.String a2) {
            record("registerListener", new Object[] {a0, a1, a2});
            return false;
        }
        @Override
        public boolean unRegisterListenerType(int a0, android.app.IDataListener a1) {
            record("unRegisterListenerType", new Object[] {a0, a1});
            return false;
        }
        @Override
        public boolean unRegisterListener(android.app.IDataListener a0) {
            record("unRegisterListener", new Object[] {a0});
            return false;
        }
        @Override
        public android.app.SceneData getTypeLastReport(int a0) {
            record("getTypeLastReport", new Object[] {a0});
            return null;
        }
    }

    static final class ImplIUnFreezeCallback extends android.app.IUnFreezeCallback.Stub {
        @Override
        public void onUnFreeze(int a0) {
            record("onUnFreeze", new Object[] {a0});
        }
    }

    static final class ImplIBluetoothPan extends android.bluetooth.IBluetoothPan.Stub {
        @Override
        public boolean isTetheringOn() {
            record("isTetheringOn", new Object[] {});
            return false;
        }
        @Override
        public void setBluetoothTethering(boolean a0, java.lang.String a1) {
            record("setBluetoothTethering", new Object[] {a0, a1});
        }
        @Override
        public boolean connect(android.bluetooth.BluetoothDevice a0) {
            record("connect", new Object[] {a0});
            return false;
        }
        @Override
        public boolean disconnect(android.bluetooth.BluetoothDevice a0) {
            record("disconnect", new Object[] {a0});
            return false;
        }
        @Override
        public java.util.List getConnectedDevices() {
            record("getConnectedDevices", new Object[] {});
            return null;
        }
        @Override
        public java.util.List getDevicesMatchingConnectionStates(int[] a0) {
            record("getDevicesMatchingConnectionStates", new Object[] {a0});
            return null;
        }
        @Override
        public int getConnectionState(android.bluetooth.BluetoothDevice a0) {
            record("getConnectionState", new Object[] {a0});
            return 0;
        }
    }

    static final class ImplIPackageManagerMonitorEx extends android.content.pm.IPackageManagerMonitorEx.Stub {
    }

    static final class ImplIVirtualInputService extends android.dvr.IVirtualInputService.Stub {
        @Override
        public void attachDevice(android.os.IBinder a0, int a1, int a2) {
            record("attachDevice", new Object[] {a0, a1, a2});
        }
        @Override
        public int createDevice(android.os.IBinder a0, int a1) {
            record("createDevice", new Object[] {a0, a1});
            return 0;
        }
        @Override
        public void destoryDevice(int a0) {
            record("destoryDevice", new Object[] {a0});
        }
        @Override
        public void touch(int a0, float a1, float a2, float a3, int a4) {
            record("touch", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void singleTouch(int a0, float a1, float a2, int a3) {
            record("singleTouch", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public void buttonState(int a0, int a1) {
            record("buttonState", new Object[] {a0, a1});
        }
        @Override
        public void scroll(int a0, float a1, float a2) {
            record("scroll", new Object[] {a0, a1, a2});
        }
        @Override
        public void key(int a0, int a1, int a2) {
            record("key", new Object[] {a0, a1, a2});
        }
        @Override
        public void mouse(int a0, int a1, int a2, float a3, float a4) {
            record("mouse", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void mouseClick(int a0, int a1, int a2) {
            record("mouseClick", new Object[] {a0, a1, a2});
        }
        @Override
        public void mouseMove(int a0, float a1, float a2) {
            record("mouseMove", new Object[] {a0, a1, a2});
        }
        @Override
        public void scale(int a0, float a1) {
            record("scale", new Object[] {a0, a1});
        }
        @Override
        public void attachInitDevice(android.os.IBinder a0, int a1, int a2, int a3, int a4) {
            record("attachInitDevice", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void axis(int a0, int a1, float a2) {
            record("axis", new Object[] {a0, a1, a2});
        }
    }

    static final class ImplINetworkStatsService extends android.net.INetworkStatsService.Stub {
        @Override
        public android.net.INetworkStatsSession openSession() {
            record("openSession", new Object[] {});
            return null;
        }
        @Override
        public android.net.INetworkStatsSession openSessionForUsageStats(int a0, java.lang.String a1) {
            record("openSessionForUsageStats", new Object[] {a0, a1});
            return null;
        }
        @Override
        public android.net.NetworkStats getDataLayerSnapshotForUid(int a0) {
            record("getDataLayerSnapshotForUid", new Object[] {a0});
            return null;
        }
        @Override
        public android.net.NetworkStats getDetailedUidStats(java.lang.String[] a0) {
            record("getDetailedUidStats", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String[] getMobileIfaces() {
            record("getMobileIfaces", new Object[] {});
            return null;
        }
        @Override
        public void incrementOperationCount(int a0, int a1, int a2) {
            record("incrementOperationCount", new Object[] {a0, a1, a2});
        }
        @Override
        public void forceUpdateIfaces(android.net.Network[] a0, android.net.NetworkState[] a1, java.lang.String a2) {
            record("forceUpdateIfaces", new Object[] {a0, a1, a2});
        }
        @Override
        public void forceUpdate() {
            record("forceUpdate", new Object[] {});
        }
        @Override
        public android.net.DataUsageRequest registerUsageCallback(java.lang.String a0, android.net.DataUsageRequest a1, android.os.Messenger a2, android.os.IBinder a3) {
            record("registerUsageCallback", new Object[] {a0, a1, a2, a3});
            return null;
        }
        @Override
        public void unregisterUsageRequest(android.net.DataUsageRequest a0) {
            record("unregisterUsageRequest", new Object[] {a0});
        }
        @Override
        public long getUidStats(int a0, int a1) {
            record("getUidStats", new Object[] {a0, a1});
            return 0L;
        }
        @Override
        public long getIfaceStats(java.lang.String a0, int a1) {
            record("getIfaceStats", new Object[] {a0, a1});
            return 0L;
        }
        @Override
        public long getTotalStats(int a0) {
            record("getTotalStats", new Object[] {a0});
            return 0L;
        }
    }

    static final class ImplIDeviceIdleControllerSmtEx extends android.os.IDeviceIdleControllerSmtEx.Stub {
        @Override
        public void setDozeMode(boolean a0, boolean a1) {
            record("setDozeMode", new Object[] {a0, a1});
        }
    }

    static final class ImplIPowerAdvisor extends android.os.IPowerAdvisor.Stub {
        @Override
        public void updateAppLaunchPrediction(java.lang.String[] a0, int[] a1, float[] a2) {
            record("updateAppLaunchPrediction", new Object[] {a0, a1, a2});
        }
        @Override
        public void updateDefaultWhitelist(java.lang.String[] a0) {
            record("updateDefaultWhitelist", new Object[] {a0});
        }
        @Override
        public java.lang.String[] getDefaultWhitelist() {
            record("getDefaultWhitelist", new Object[] {});
            return null;
        }
        @Override
        public void userSelectedWhitelistApp(java.lang.String a0) {
            record("userSelectedWhitelistApp", new Object[] {a0});
        }
        @Override
        public int getLongTimeNoResumeDay() {
            record("getLongTimeNoResumeDay", new Object[] {});
            return 0;
        }
        @Override
        public void notifyLongTimeNoResumeApp(java.lang.String[] a0) {
            record("notifyLongTimeNoResumeApp", new Object[] {a0});
        }
        @Override
        public boolean inPowerCheckBlacklist(java.lang.String a0, int a1) {
            record("inPowerCheckBlacklist", new Object[] {a0, a1});
            return false;
        }
        @Override
        public void updateSleepPrediction(int a0, float a1) {
            record("updateSleepPrediction", new Object[] {a0, a1});
        }
        @Override
        public boolean isSleepModeSupport() {
            record("isSleepModeSupport", new Object[] {});
            return false;
        }
        @Override
        public void notifyLockFreqState(boolean a0) {
            record("notifyLockFreqState", new Object[] {a0});
        }
        @Override
        public void enterEnduranceMode(java.util.Map a0) {
            record("enterEnduranceMode", new Object[] {a0});
        }
        @Override
        public void notePowerSceneState(java.lang.String a0, java.lang.String a1, java.lang.String a2, int a3, java.lang.String a4) {
            record("notePowerSceneState", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public boolean enableWifi(java.lang.String a0, int a1) {
            record("enableWifi", new Object[] {a0, a1});
            return false;
        }
        @Override
        public void disableWifi(java.lang.String a0) {
            record("disableWifi", new Object[] {a0});
        }
        @Override
        public void noteSystemState(java.lang.String a0, java.lang.String a1, java.lang.String a2) {
            record("noteSystemState", new Object[] {a0, a1, a2});
        }
    }

    static final class ImplIStatsManager extends android.os.IStatsManager.Stub {
        @Override
        public void systemRunning() {
            record("systemRunning", new Object[] {});
        }
        @Override
        public void statsCompanionReady() {
            record("statsCompanionReady", new Object[] {});
        }
        @Override
        public void informAnomalyAlarmFired() {
            record("informAnomalyAlarmFired", new Object[] {});
        }
        @Override
        public void informPollAlarmFired() {
            record("informPollAlarmFired", new Object[] {});
        }
        @Override
        public void informAlarmForSubscriberTriggeringFired() {
            record("informAlarmForSubscriberTriggeringFired", new Object[] {});
        }
        @Override
        public void informDeviceShutdown() {
            record("informDeviceShutdown", new Object[] {});
        }
        @Override
        public void informAllUidData(android.os.ParcelFileDescriptor a0) {
            record("informAllUidData", new Object[] {a0});
        }
        @Override
        public void informOnePackage(java.lang.String a0, int a1, long a2, java.lang.String a3, java.lang.String a4) {
            record("informOnePackage", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void informOnePackageRemoved(java.lang.String a0, int a1) {
            record("informOnePackageRemoved", new Object[] {a0, a1});
        }
        @Override
        public byte[] getData(long a0, java.lang.String a1) {
            record("getData", new Object[] {a0, a1});
            return null;
        }
        @Override
        public byte[] getMetadata(java.lang.String a0) {
            record("getMetadata", new Object[] {a0});
            return null;
        }
        @Override
        public void addConfiguration(long a0, byte[] a1, java.lang.String a2) {
            record("addConfiguration", new Object[] {a0, a1, a2});
        }
        @Override
        public void setDataFetchOperation(long a0, android.os.IBinder a1, java.lang.String a2) {
            record("setDataFetchOperation", new Object[] {a0, a1, a2});
        }
        @Override
        public void removeDataFetchOperation(long a0, java.lang.String a1) {
            record("removeDataFetchOperation", new Object[] {a0, a1});
        }
        @Override
        public long[] setActiveConfigsChangedOperation(android.os.IBinder a0, java.lang.String a1) {
            record("setActiveConfigsChangedOperation", new Object[] {a0, a1});
            return null;
        }
        @Override
        public void removeActiveConfigsChangedOperation(java.lang.String a0) {
            record("removeActiveConfigsChangedOperation", new Object[] {a0});
        }
        @Override
        public void removeConfiguration(long a0, java.lang.String a1) {
            record("removeConfiguration", new Object[] {a0, a1});
        }
        @Override
        public void setBroadcastSubscriber(long a0, long a1, android.os.IBinder a2, java.lang.String a3) {
            record("setBroadcastSubscriber", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public void unsetBroadcastSubscriber(long a0, long a1, java.lang.String a2) {
            record("unsetBroadcastSubscriber", new Object[] {a0, a1, a2});
        }
        @Override
        public void sendAppBreadcrumbAtom(int a0, int a1) {
            record("sendAppBreadcrumbAtom", new Object[] {a0, a1});
        }
        @Override
        public void registerPullerCallback(int a0, android.os.IStatsPullerCallback a1, java.lang.String a2) {
            record("registerPullerCallback", new Object[] {a0, a1, a2});
        }
        @Override
        public void unregisterPullerCallback(int a0, java.lang.String a1) {
            record("unregisterPullerCallback", new Object[] {a0, a1});
        }
        @Override
        public void sendBinaryPushStateChangedAtom(java.lang.String a0, long a1, int a2, int a3, long[] a4) {
            record("sendBinaryPushStateChangedAtom", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void sendWatchdogRollbackOccurredAtom(int a0, java.lang.String a1, long a2, int a3, java.lang.String a4) {
            record("sendWatchdogRollbackOccurredAtom", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public long[] getRegisteredExperimentIds() {
            record("getRegisteredExperimentIds", new Object[] {});
            return null;
        }
    }

    static final class ImplIVibratorService extends android.os.IVibratorService.Stub {
        @Override
        public boolean hasVibrator() {
            record("hasVibrator", new Object[] {});
            return false;
        }
        @Override
        public boolean hasAmplitudeControl() {
            record("hasAmplitudeControl", new Object[] {});
            return false;
        }
        @Override
        public void vibrate(int a0, java.lang.String a1, android.os.VibrationEffect a2, android.media.AudioAttributes a3, java.lang.String a4, android.os.IBinder a5) {
            record("vibrate", new Object[] {a0, a1, a2, a3, a4, a5});
        }
        @Override
        public void cancelVibrate(android.os.IBinder a0) {
            record("cancelVibrate", new Object[] {a0});
        }
    }

    static final class ImplISmtPCManager extends android.pc.ISmtPCManager.Stub {
        @Override
        public int getCurrentExtDisplayId() {
            record("getCurrentExtDisplayId", new Object[] {});
            return 0;
        }
    }

    static final class ImplISystemGestureExclusionListener extends android.view.ISystemGestureExclusionListener.Stub {
        @Override
        public void onSystemGestureExclusionChanged(int a0, android.graphics.Region a1, android.graphics.Region a2) {
            record("onSystemGestureExclusionChanged", new Object[] {a0, a1, a2});
        }
    }

    static final class ImplISysTransServer extends com.android.internal.app.ISysTransServer.Stub {
        @Override
        public void requestChangeDisplayFps(int a0, int a1, int a2) {
            record("requestChangeDisplayFps", new Object[] {a0, a1, a2});
        }
        @Override
        public void notifyDisplayFpsResult(int a0, int a1, int a2) {
            record("notifyDisplayFpsResult", new Object[] {a0, a1, a2});
        }
        @Override
        public void notifyDisplayTpResult(int a0, int a1, int a2) {
            record("notifyDisplayTpResult", new Object[] {a0, a1, a2});
        }
        @Override
        public int[] getCalculationConfig() {
            record("getCalculationConfig", new Object[] {});
            return null;
        }
        @Override
        public void setProcessRunningCpuset(int a0, int a1, long a2, boolean a3) {
            record("setProcessRunningCpuset", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public void notifyVirtualDisplaySurfaceChanged(int a0, java.lang.String a1) {
            record("notifyVirtualDisplaySurfaceChanged", new Object[] {a0, a1});
        }
    }

    static final class ImplITransferServer extends com.android.internal.app.ITransferServer.Stub {
        @Override
        public void reportAlarm(int a0, int a1, int a2, int a3, int a4, long a5, long a6, long a7, java.lang.String a8, int a9) {
            record("reportAlarm", new Object[] {a0, a1, a2, a3, a4, a5, a6, a7, a8, a9});
        }
        @Override
        public void reportGameBalanceConfig(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, java.lang.String a4, double a5, double a6) {
            record("reportGameBalanceConfig", new Object[] {a0, a1, a2, a3, a4, a5, a6});
        }
        @Override
        public void reportGameBalanceFps(java.lang.String a0, java.lang.String a1) {
            record("reportGameBalanceFps", new Object[] {a0, a1});
        }
        @Override
        public void reportJunk(int a0, int a1, int a2, long a3, long a4, long a5, java.lang.String a6) {
            record("reportJunk", new Object[] {a0, a1, a2, a3, a4, a5, a6});
        }
        @Override
        public void reportFps(int a0, double a1, java.lang.String a2, int a3, long a4, int a5) {
            record("reportFps", new Object[] {a0, a1, a2, a3, a4, a5});
        }
        @Override
        public void reportInputHang(java.util.List a0, float[] a1, long a2) {
            record("reportInputHang", new Object[] {a0, a1, a2});
        }
        @Override
        public void requestGameAtrace(java.lang.String a0) {
            record("requestGameAtrace", new Object[] {a0});
        }
        @Override
        public void reportAppMainTerribleMsg(java.util.List a0, int a1, long a2) {
            record("reportAppMainTerribleMsg", new Object[] {a0, a1, a2});
        }
        @Override
        public void reportUnityFpsList(int a0, int[] a1, int a2) {
            record("reportUnityFpsList", new Object[] {a0, a1, a2});
        }
        @Override
        public void reportFirstFrameCompleted(int a0, long a1) {
            record("reportFirstFrameCompleted", new Object[] {a0, a1});
        }
        @Override
        public void reportAlgCostBad(int a0, int a1) {
            record("reportAlgCostBad", new Object[] {a0, a1});
        }
        @Override
        public void startPerfetto(int a0) {
            record("startPerfetto", new Object[] {a0});
        }
        @Override
        public void dumpPerfetto(java.lang.String a0) {
            record("dumpPerfetto", new Object[] {a0});
        }
        @Override
        public void startPerfettoForce(int a0) {
            record("startPerfettoForce", new Object[] {a0});
        }
        @Override
        public int startPerfettoFromMTP(java.lang.String a0, int a1, int a2, int a3, int a4, boolean a5) {
            record("startPerfettoFromMTP", new Object[] {a0, a1, a2, a3, a4, a5});
            return 0;
        }
        @Override
        public int dumpPerfettoFromMTP(java.lang.String a0, int a1, int a2, int a3, int a4, boolean a5, boolean a6, long a7) {
            record("dumpPerfettoFromMTP", new Object[] {a0, a1, a2, a3, a4, a5, a6, a7});
            return 0;
        }
        @Override
        public int dumpSystemInfo(java.lang.String a0, int a1, int a2, int a3, int a4) {
            record("dumpSystemInfo", new Object[] {a0, a1, a2, a3, a4});
            return 0;
        }
        @Override
        public void startPerfettoFromUserReport(java.lang.String a0) {
            record("startPerfettoFromUserReport", new Object[] {a0});
        }
        @Override
        public void reportFocusAppChanged(java.lang.String a0) {
            record("reportFocusAppChanged", new Object[] {a0});
        }
        @Override
        public void reportEvent(int a0, int a1, float a2, int a3, java.lang.String a4, int a5, long[] a6) {
            record("reportEvent", new Object[] {a0, a1, a2, a3, a4, a5, a6});
        }
        @Override
        public float[] getMuduleEventInfo(int a0) {
            record("getMuduleEventInfo", new Object[] {a0});
            return null;
        }
        @Override
        public void chmodSyslogDir() {
            record("chmodSyslogDir", new Object[] {});
        }
        @Override
        public void reportThreadTID(int a0, int a1, java.lang.String a2) {
            record("reportThreadTID", new Object[] {a0, a1, a2});
        }
        @Override
        public float getGPUUtilization(int a0, int a1) {
            record("getGPUUtilization", new Object[] {a0, a1});
            return 0f;
        }
        @Override
        public float getGPUPeak() {
            record("getGPUPeak", new Object[] {});
            return 0f;
        }
        @Override
        public int setPerfettoStatusForLab(java.lang.String a0, int a1, int a2, int a3, int a4) {
            record("setPerfettoStatusForLab", new Object[] {a0, a1, a2, a3, a4});
            return 0;
        }
        @Override
        public int[] getGPUInfo() {
            record("getGPUInfo", new Object[] {});
            return null;
        }
        @Override
        public int dumpSchedInfoFromMTP(int a0, int a1, int a2, int a3) {
            record("dumpSchedInfoFromMTP", new Object[] {a0, a1, a2, a3});
            return 0;
        }
        @Override
        public int getGPULoad() {
            record("getGPULoad", new Object[] {});
            return 0;
        }
        @Override
        public void updateAppDisplayRefresh(java.lang.String a0, int a1, float a2, float a3, boolean a4) {
            record("updateAppDisplayRefresh", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void reportVSTStatus(int a0, int a1) {
            record("reportVSTStatus", new Object[] {a0, a1});
        }
    }

    static final class ImplICarStatsService extends com.android.internal.car.ICarStatsService.Stub {
        @Override
        public android.os.StatsLogEventWrapper[] pullData(int a0) {
            record("pullData", new Object[] {a0});
            return null;
        }
    }

    static final class ImplIKeyguardFaceIDVerifyCallback extends com.android.internal.policy.IKeyguardFaceIDVerifyCallback.Stub {
        @Override
        public void onFaceAuthenticationSucceeded() {
            record("onFaceAuthenticationSucceeded", new Object[] {});
        }
    }

    static final class ImplIKeyguardFingerprintVerifyCallback extends com.android.internal.policy.IKeyguardFingerprintVerifyCallback.Stub {
        @Override
        public void onAuthenticationFailed() {
            record("onAuthenticationFailed", new Object[] {});
        }
        @Override
        public void onAuthenticationSucceeded() {
            record("onAuthenticationSucceeded", new Object[] {});
        }
        @Override
        public void onAuthenticationHelp(int a0, java.lang.CharSequence a1) {
            record("onAuthenticationHelp", new Object[] {a0, a1});
        }
        @Override
        public void onAuthenticationError(int a0, java.lang.CharSequence a1) {
            record("onAuthenticationError", new Object[] {a0, a1});
        }
        @Override
        public void onAuthenticationAcquired(int a0) {
            record("onAuthenticationAcquired", new Object[] {a0});
        }
    }

    static final class ImplIKeyguardVerifyCallback extends com.android.internal.policy.IKeyguardVerifyCallback.Stub {
        @Override
        public void onKeyguardVerifyResult(boolean a0, int a1) {
            record("onKeyguardVerifyResult", new Object[] {a0, a1});
        }
    }
}
