// Copyright 2026 Picomisu contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by tools/generate-pico-api-fixture.py; do not edit.
package org.picomisu.runtime;

import android.content.ComponentName;
import android.os.Bundle;
import android.os.IBinder;
import android.os.Parcel;
import android.os.Parcelable;

import java.io.PrintStream;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Proxy;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * Wire-format scenarios for the PICO framework AIDL interfaces and parcelables. The same
 * probe JAR runs on the factory and the Source framework; lines "pico-api key=value" are
 * compared by tools/compare-pico-api-runtime.py.
 */
public final class PicoApiFixture {
    static final int EXPECTED_LINES = 313;
    private static PrintStream sOut;
    private static int sLines;
    private static String sRecorded;

    private PicoApiFixture() {}

    public static void main(String[] args) throws Exception {
        System.out.println("pico-api-fixture lines=" + run(System.out));
    }

    static void emit(String key, Object value) {
        sOut.println("pico-api " + key + "=" + value);
        sLines++;
    }

    static void record(String name, Object[] args) {
        sRecorded = name + describe(args);
    }

    static String hex(Parcel parcel) {
        StringBuilder text = new StringBuilder();
        for (byte b : parcel.marshall()) {
            text.append(String.format("%02x", b & 0xff));
        }
        return text.toString();
    }

    static String describe(Object value) {
        if (value == null) return "null";
        if (value instanceof Object[]) {
            StringBuilder text = new StringBuilder("[");
            for (Object item : (Object[]) value) text.append(describe(item)).append(',');
            return text.append(']').toString();
        }
        if (value instanceof int[]) return Arrays.toString((int[]) value);
        if (value instanceof long[]) return Arrays.toString((long[]) value);
        if (value instanceof byte[]) return Arrays.toString((byte[]) value);
        if (value instanceof boolean[]) return Arrays.toString((boolean[]) value);
        if (value instanceof float[]) return Arrays.toString((float[]) value);
        if (value instanceof Bundle) {
            Bundle bundle = (Bundle) value;
            List<String> keys = new ArrayList<>(bundle.keySet());
            keys.sort(null);
            StringBuilder text = new StringBuilder("Bundle{");
            for (String key : keys) text.append(key).append('=').append(bundle.get(key)).append(';');
            return text.append('}').toString();
        }
        if (value instanceof Parcelable) {
            Parcel parcel = Parcel.obtain();
            ((Parcelable) value).writeToParcel(parcel, 0);
            String result = value.getClass().getName() + ":" + hex(parcel);
            parcel.recycle();
            return result;
        }
        return String.valueOf(value);
    }

    static Object argument(Class<?> type, int index) {
        if (type == int.class) return 0x11223340 + index;
        if (type == long.class) return 0x1122334455667700L + index;
        if (type == boolean.class) return index % 2 == 0;
        if (type == byte.class) return (byte) (0x40 + index);
        if (type == float.class) return 1.5f + index;
        if (type == double.class) return 2.5d + index;
        if (type == String.class) return "s" + index;
        if (type == String[].class) return new String[] {"a" + index, "b" + index};
        if (type == int[].class) return new int[] {index, index + 1};
        if (type == Bundle.class) {
            Bundle bundle = new Bundle();
            bundle.putString("k" + index, "v" + index);
            return bundle;
        }
        if (type == ComponentName.class) return new ComponentName("org.picomisu", "org.picomisu.C" + index);
        return null;
    }

    /** IBinder that records transactions and answers with an empty no-exception reply. */
    static final class Wire {
        int code;
        int flags;
        String data;
        byte[] raw;

        IBinder binder() {
            return (IBinder) Proxy.newProxyInstance(IBinder.class.getClassLoader(),
                    new Class<?>[] {IBinder.class}, (proxy, method, values) -> {
                        switch (method.getName()) {
                            case "transact": {
                                code = (Integer) values[0];
                                flags = (Integer) values[3];
                                Parcel in = (Parcel) values[1];
                                raw = in.marshall();
                                data = hex(in);
                                Parcel reply = (Parcel) values[2];
                                if (reply != null) {
                                    reply.writeNoException();
                                    for (int i = 0; i < 16; ++i) reply.writeInt(0);
                                    reply.setDataPosition(0);
                                }
                                return true;
                            }
                            case "queryLocalInterface": return null;
                            case "isBinderAlive": case "pingBinder": return true;
                            case "linkToDeath": return null;
                            case "unlinkToDeath": return true;
                            case "getInterfaceDescriptor": return "wire";
                            default: return null;
                        }
                    });
        }
    }

    static int run(PrintStream out) throws Exception {
        sOut = out;
        sLines = 0;
        for (Object[] entry : REGISTRY) {
            interfaceScenarios((String) entry[0], (Class<?>) entry[1], (Integer) entry[2]);
        }
        for (String name : PARCELABLES) {
            parcelable(name);
        }
        return sLines;
    }

    private static void interfaceScenarios(String name, Class<?> implementation, int count)
            throws Exception {
        Class<?> api = Class.forName(name);
        Class<?> stub = Class.forName(name + "$Stub");
        Wire wire = new Wire();
        Object proxy = stub.getMethod("asInterface", IBinder.class).invoke(null, wire.binder());
        Object local = implementation.getDeclaredConstructor().newInstance();
        emit(name + ".descriptor", ((IBinder) local).getInterfaceDescriptor());
        Method[] methods = api.getDeclaredMethods();
        Arrays.sort(methods, Comparator.comparing(Method::toGenericString));
        int seen = 0;
        for (Method method : methods) {
            if (Modifier.isStatic(method.getModifiers())) continue;
            seen++;
            Class<?>[] types = method.getParameterTypes();
            Object[] values = new Object[types.length];
            for (int i = 0; i < types.length; ++i) values[i] = argument(types[i], i);
            String key = name + "." + method.getName() + "/" + types.length;
            String result;
            try {
                result = describe(method.invoke(proxy, values));
            } catch (InvocationTargetException e) {
                result = "exception:" + e.getCause().getClass().getName();
            }
            emit(key + ".proxy", wire.code + "/" + wire.flags + "/" + wire.data + "/" + result);
            Parcel data = Parcel.obtain();
            data.unmarshall(wire.raw, 0, wire.raw.length);
            data.setDataPosition(0);
            Parcel reply = Parcel.obtain();
            sRecorded = null;
            String handled;
            try {
                Method onTransact = stub.getMethod("onTransact", int.class, Parcel.class, Parcel.class,
                        int.class);
                handled = String.valueOf(onTransact.invoke(local, wire.code, data, reply, wire.flags));
            } catch (InvocationTargetException e) {
                handled = "exception:" + e.getCause().getClass().getName();
            }
            emit(key + ".stub", handled + "/" + sRecorded + "/" + hex(reply));
            data.recycle();
            reply.recycle();
        }
        if (seen != count) throw new AssertionError("Unexpected method count for " + name);
    }

    private static Object unsafeAllocate(Class<?> type) throws Exception {
        Class<?> unsafeType = Class.forName("sun.misc.Unsafe");
        Field field;
        try {
            field = unsafeType.getDeclaredField("THE_ONE");
        } catch (NoSuchFieldException e) {
            field = unsafeType.getDeclaredField("theUnsafe");
        }
        field.setAccessible(true);
        Object unsafe = field.get(null);
        return unsafeType.getMethod("allocateInstance", Class.class).invoke(unsafe, type);
    }

    /** Fill every instance field deterministically, then marshal, unmarshal and marshal again. */
    private static void parcelable(String name) throws Exception {
        Class<?> type = Class.forName(name);
        Object value = unsafeAllocate(type);
        int index = 0;
        for (Class<?> c = type; c != null && c != Object.class; c = c.getSuperclass()) {
            Field[] fields = c.getDeclaredFields();
            Arrays.sort(fields, Comparator.comparing(Field::getName));
            for (Field field : fields) {
                if (Modifier.isStatic(field.getModifiers())) continue;
                field.setAccessible(true);
                Class<?> t = field.getType();
                index++;
                if (t == int.class) field.setInt(value, index * 7);
                else if (t == long.class) field.setLong(value, index * 1000003L);
                else if (t == boolean.class) field.setBoolean(value, index % 2 == 1);
                else if (t == float.class) field.setFloat(value, index + 0.25f);
                else if (t == double.class) field.setDouble(value, index + 0.5d);
                else if (t == byte.class) field.setByte(value, (byte) index);
                else if (t == short.class) field.setShort(value, (short) index);
                else if (t == String.class) field.set(value, field.getName() + index);
            }
        }
        Parcel first = Parcel.obtain();
        ((Parcelable) value).writeToParcel(first, 0);
        String bytes = hex(first);
        first.setDataPosition(0);
        Parcelable.Creator<?> creator = (Parcelable.Creator<?>) type.getField("CREATOR").get(null);
        Object copy = creator.createFromParcel(first);
        Parcel second = Parcel.obtain();
        ((Parcelable) copy).writeToParcel(second, 0);
        emit(name + ".write", bytes);
        emit(name + ".roundtrip", hex(second).equals(bytes) + "/" + first.dataAvail());
        first.recycle();
        second.recycle();
    }

    private static final String[] PARCELABLES = {"com.pxr.bluetooth.BluetoothPxrDeviceProperty", "com.pxr.net.LinkLayerQuality", "com.pxr.net.NetworkQuality", "com.pxr.net.PxrWifiConnectionInfo"};

    private static final Object[][] REGISTRY = {
        {"com.pico.api.app.IApiLayer", ImplIApiLayer.class, 27},
        {"com.pico.api.app.IAppSession", ImplIAppSession.class, 0},
        {"com.pvr.IPvrCallback", ImplIPvrCallback.class, 1},
        {"com.pvr.IPvrCallbackNative", ImplIPvrCallbackNative.class, 1},
        {"com.pvr.IPvrManagerService", ImplIPvrManagerService.class, 20},
        {"com.pvr.ISysDataSyncService", ImplISysDataSyncService.class, 9},
        {"com.pvr.configuration.IConfigServiceInterface", ImplIConfigServiceInterface.class, 71},
        {"com.pxr.bluetooth.IBluetoothPxr", ImplIBluetoothPxr.class, 2},
        {"com.pxr.bluetooth.IBluetoothPxrDeviceCallback", ImplIBluetoothPxrDeviceCallback.class, 2},
        {"com.pxr.net.ILinkLayerQualityListener", ImplILinkLayerQualityListener.class, 3},
        {"com.pxr.net.INetworkQualityListener", ImplINetworkQualityListener.class, 1},
        {"com.pxr.net.IPxrNetworkManager", ImplIPxrNetworkManager.class, 7},
        {"com.pxr.pxrapi.IScreenCaptureInterface", ImplIScreenCaptureInterface.class, 2},
    };

    static final class ImplIApiLayer extends com.pico.api.app.IApiLayer.Stub {
        @Override
        public boolean getScreenState() {
            record("getScreenState", new Object[] {});
            return false;
        }
        @Override
        public boolean isInputMethodShowing() {
            record("isInputMethodShowing", new Object[] {});
            return false;
        }
        @Override
        public int getSeethroughState() {
            record("getSeethroughState", new Object[] {});
            return 0;
        }
        @Override
        public java.lang.String getShowing3dApp() {
            record("getShowing3dApp", new Object[] {});
            return null;
        }
        @Override
        public int getXrRuntimeDisplayState() {
            record("getXrRuntimeDisplayState", new Object[] {});
            return 0;
        }
        @Override
        public java.lang.String getRunning2dAppData() {
            record("getRunning2dAppData", new Object[] {});
            return null;
        }
        @Override
        public android.content.ComponentName getTopAppOnDefaultDisplay() {
            record("getTopAppOnDefaultDisplay", new Object[] {});
            return null;
        }
        @Override
        public void updatePersistentServiceConnection(android.content.ComponentName a0, boolean a1) {
            record("updatePersistentServiceConnection", new Object[] {a0, a1});
        }
        @Override
        public void registerAppSession(android.os.IBinder a0, int a1) {
            record("registerAppSession", new Object[] {a0, a1});
        }
        @Override
        public void unregisterAppSession(android.os.IBinder a0, int a1) {
            record("unregisterAppSession", new Object[] {a0, a1});
        }
        @Override
        public void updateSeethroughState(int a0) {
            record("updateSeethroughState", new Object[] {a0});
        }
        @Override
        public void updateRunning2dAppList(java.lang.String a0) {
            record("updateRunning2dAppList", new Object[] {a0});
        }
        @Override
        public void updateShowing3dApp(java.lang.String a0) {
            record("updateShowing3dApp", new Object[] {a0});
        }
        @Override
        public void updateXrRuntimeState(android.os.Bundle a0) {
            record("updateXrRuntimeState", new Object[] {a0});
        }
        @Override
        public java.lang.String getTopAppOnDefaultDisplayForNative() {
            record("getTopAppOnDefaultDisplayForNative", new Object[] {});
            return null;
        }
        @Override
        public int getPowerState() {
            record("getPowerState", new Object[] {});
            return 0;
        }
        @Override
        public int getSettingsInt(int a0, java.lang.String a1, int a2) {
            record("getSettingsInt", new Object[] {a0, a1, a2});
            return 0;
        }
        @Override
        public void putSettingsInt(int a0, java.lang.String a1, int a2) {
            record("putSettingsInt", new Object[] {a0, a1, a2});
        }
        @Override
        public java.lang.String getSettingsString(int a0, java.lang.String a1) {
            record("getSettingsString", new Object[] {a0, a1});
            return null;
        }
        @Override
        public void putSettingsString(int a0, java.lang.String a1, java.lang.String a2) {
            record("putSettingsString", new Object[] {a0, a1, a2});
        }
        @Override
        public void registerSettingsObserverForNative(android.os.IBinder a0, int a1, java.lang.String a2, int a3) {
            record("registerSettingsObserverForNative", new Object[] {a0, a1, a2, a3});
        }
        @Override
        public void unregisterSettingsObserverForNative(android.os.IBinder a0, int a1, java.lang.String a2) {
            record("unregisterSettingsObserverForNative", new Object[] {a0, a1, a2});
        }
        @Override
        public void startActivityForNative(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, int a4) {
            record("startActivityForNative", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void startServiceForNative(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, int a4) {
            record("startServiceForNative", new Object[] {a0, a1, a2, a3, a4});
        }
        @Override
        public void registerBroadcastReceiverForNative(android.os.IBinder a0, java.lang.String a1, java.lang.String a2) {
            record("registerBroadcastReceiverForNative", new Object[] {a0, a1, a2});
        }
        @Override
        public void unregisterBroadcastReceiverForNative(android.os.IBinder a0, java.lang.String a1) {
            record("unregisterBroadcastReceiverForNative", new Object[] {a0, a1});
        }
        @Override
        public void requestShowAnrDialog(java.lang.String a0, android.os.RemoteCallback a1) {
            record("requestShowAnrDialog", new Object[] {a0, a1});
        }
    }

    static final class ImplIAppSession extends com.pico.api.app.IAppSession.Stub {
    }

    static final class ImplIPvrCallback extends com.pvr.IPvrCallback.Stub {
        @Override
        public void onEventChanged(android.os.Bundle a0) {
            record("onEventChanged", new Object[] {a0});
        }
    }

    static final class ImplIPvrCallbackNative extends com.pvr.IPvrCallbackNative.Stub {
        @Override
        public void onEventChanged(java.lang.String a0, java.lang.String a1) {
            record("onEventChanged", new Object[] {a0, a1});
        }
    }

    static final class ImplIPvrManagerService extends com.pvr.IPvrManagerService.Stub {
        @Override
        public boolean setSystemFeatures(int a0, java.lang.String a1, android.os.IBinder a2) {
            record("setSystemFeatures", new Object[] {a0, a1, a2});
            return false;
        }
        @Override
        public boolean addSystemService(java.lang.String a0, android.os.IBinder a1, android.os.IBinder a2) {
            record("addSystemService", new Object[] {a0, a1, a2});
            return false;
        }
        @Override
        public java.lang.String getSystemFeatures(int a0, android.os.IBinder a1) {
            record("getSystemFeatures", new Object[] {a0, a1});
            return null;
        }
        @Override
        public void addPvrCallback(java.lang.String a0, com.pvr.IPvrCallback a1, int a2) {
            record("addPvrCallback", new Object[] {a0, a1, a2});
        }
        @Override
        public void removePvrCallback(java.lang.String a0) {
            record("removePvrCallback", new Object[] {a0});
        }
        @Override
        public void sendPvrMessage(java.lang.String a0, java.lang.String a1, int a2) {
            record("sendPvrMessage", new Object[] {a0, a1, a2});
        }
        @Override
        public void updateUserSettings(java.lang.String a0, boolean a1) {
            record("updateUserSettings", new Object[] {a0, a1});
        }
        @Override
        public int[] getScreenBrightnessLevel() {
            record("getScreenBrightnessLevel", new Object[] {});
            return null;
        }
        @Override
        public void setCurrentScreenBrightnessLevel(int a0, int a1) {
            record("setCurrentScreenBrightnessLevel", new Object[] {a0, a1});
        }
        @Override
        public int setLedStatus(int a0, int a1, int a2, int a3, int a4) {
            record("setLedStatus", new Object[] {a0, a1, a2, a3, a4});
            return 0;
        }
        @Override
        public int getHeadstrapStatus() {
            record("getHeadstrapStatus", new Object[] {});
            return 0;
        }
        @Override
        public void addPvrCallbacks(com.pvr.IPvrCallback a0) {
            record("addPvrCallbacks", new Object[] {a0});
        }
        @Override
        public void removePvrCallbacks(int a0) {
            record("removePvrCallbacks", new Object[] {a0});
        }
        @Override
        public void sendPvrMessages(java.lang.String a0, java.lang.String a1) {
            record("sendPvrMessages", new Object[] {a0, a1});
        }
        @Override
        public void updateDistributionChannel(java.lang.String a0, boolean a1) {
            record("updateDistributionChannel", new Object[] {a0, a1});
        }
        @Override
        public void addPvrCallbacksNative(com.pvr.IPvrCallbackNative a0) {
            record("addPvrCallbacksNative", new Object[] {a0});
        }
        @Override
        public void setClientStatus(int a0) {
            record("setClientStatus", new Object[] {a0});
        }
        @Override
        public void sendEvent(java.lang.String a0, android.os.Bundle a1) {
            record("sendEvent", new Object[] {a0, a1});
        }
        @Override
        public void addPvrCallbacksWithEventType(com.pvr.IPvrCallback a0, java.lang.String[] a1) {
            record("addPvrCallbacksWithEventType", new Object[] {a0, a1});
        }
        @Override
        public void addPvrCallbacksNativeWithEventType(com.pvr.IPvrCallbackNative a0, java.lang.String[] a1) {
            record("addPvrCallbacksNativeWithEventType", new Object[] {a0, a1});
        }
    }

    static final class ImplISysDataSyncService extends com.pvr.ISysDataSyncService.Stub {
        @Override
        public void onUsageEvent(android.os.Bundle a0) {
            record("onUsageEvent", new Object[] {a0});
        }
        @Override
        public void onAppDied(android.os.Bundle a0) {
            record("onAppDied", new Object[] {a0});
        }
        @Override
        public void onReportAid(java.lang.String a0, java.lang.String a1) {
            record("onReportAid", new Object[] {a0, a1});
        }
        @Override
        public void onTeaTrackerEvent(java.lang.String a0, java.lang.String a1, java.lang.String a2) {
            record("onTeaTrackerEvent", new Object[] {a0, a1, a2});
        }
        @Override
        public int queryProfile(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, java.lang.String a4) {
            record("queryProfile", new Object[] {a0, a1, a2, a3, a4});
            return 0;
        }
        @Override
        public boolean uploadProfile(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, java.lang.String a4) {
            record("uploadProfile", new Object[] {a0, a1, a2, a3, a4});
            return false;
        }
        @Override
        public void onMetricEvent(java.lang.String a0, java.lang.String a1) {
            record("onMetricEvent", new Object[] {a0, a1});
        }
        @Override
        public void onSlardarEvent(java.lang.String a0, java.lang.String a1) {
            record("onSlardarEvent", new Object[] {a0, a1});
        }
        @Override
        public void flushTeaTrackerEvents() {
            record("flushTeaTrackerEvents", new Object[] {});
        }
    }

    static final class ImplIConfigServiceInterface extends com.pvr.configuration.IConfigServiceInterface.Stub {
        @Override
        public java.lang.String getConfigPropertyDirectAccess(int a0, java.lang.String a1, java.lang.String a2) {
            record("getConfigPropertyDirectAccess", new Object[] {a0, a1, a2});
            return null;
        }
        @Override
        public boolean setConfigPropertyDirectAccess(java.lang.String a0, int a1, java.lang.String a2, java.lang.String a3, java.lang.String a4, int a5) {
            record("setConfigPropertyDirectAccess", new Object[] {a0, a1, a2, a3, a4, a5});
            return false;
        }
        @Override
        public java.lang.String getConfigProperty(java.lang.String a0, int a1, java.lang.String a2, java.lang.String a3) {
            record("getConfigProperty", new Object[] {a0, a1, a2, a3});
            return null;
        }
        @Override
        public boolean setConfigProperty(java.lang.String a0, int a1, java.lang.String a2, java.lang.String a3, java.lang.String a4, int a5) {
            record("setConfigProperty", new Object[] {a0, a1, a2, a3, a4, a5});
            return false;
        }
        @Override
        public boolean updateConfiguration(java.lang.String a0, java.lang.String a1) {
            record("updateConfiguration", new Object[] {a0, a1});
            return false;
        }
        @Override
        public java.lang.String addClientProperty(java.lang.String a0, int a1) {
            record("addClientProperty", new Object[] {a0, a1});
            return null;
        }
        @Override
        public java.lang.String addClientPropertyJson(java.lang.String a0) {
            record("addClientPropertyJson", new Object[] {a0});
            return null;
        }
        @Override
        public boolean deleteClientPropertyByClientId(java.lang.String a0) {
            record("deleteClientPropertyByClientId", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteClientPropertyByPkg(java.lang.String a0) {
            record("deleteClientPropertyByPkg", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteClientProperty(java.lang.String a0) {
            record("deleteClientProperty", new Object[] {a0});
            return false;
        }
        @Override
        public boolean updateClientProperty(java.lang.String a0, int a1, java.lang.String a2, java.lang.String a3) {
            record("updateClientProperty", new Object[] {a0, a1, a2, a3});
            return false;
        }
        @Override
        public boolean updateClientPropertyJson(java.lang.String a0) {
            record("updateClientPropertyJson", new Object[] {a0});
            return false;
        }
        @Override
        public java.lang.String queryClientPropertyByClientId(java.lang.String a0) {
            record("queryClientPropertyByClientId", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryClientPropertyByPkg(java.lang.String a0) {
            record("queryClientPropertyByPkg", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryClientProperty(java.lang.String a0) {
            record("queryClientProperty", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String addClientMappingData(java.lang.String a0, java.lang.String a1, int a2) {
            record("addClientMappingData", new Object[] {a0, a1, a2});
            return null;
        }
        @Override
        public java.lang.String addClientMappingDataJson(java.lang.String a0) {
            record("addClientMappingDataJson", new Object[] {a0});
            return null;
        }
        @Override
        public boolean deleteClientMappingDataByClientId(java.lang.String a0) {
            record("deleteClientMappingDataByClientId", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteClientMappingDataByPermissionId(java.lang.String a0) {
            record("deleteClientMappingDataByPermissionId", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteClientMappingData(java.lang.String a0) {
            record("deleteClientMappingData", new Object[] {a0});
            return false;
        }
        @Override
        public boolean updateClientMappingData(java.lang.String a0, int a1, java.lang.String a2, java.lang.String a3) {
            record("updateClientMappingData", new Object[] {a0, a1, a2, a3});
            return false;
        }
        @Override
        public boolean updateClientMappingDataJson(java.lang.String a0) {
            record("updateClientMappingDataJson", new Object[] {a0});
            return false;
        }
        @Override
        public java.lang.String queryClientMappingDataByClientId(java.lang.String a0) {
            record("queryClientMappingDataByClientId", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryClientMappingDataByPermissionId(java.lang.String a0) {
            record("queryClientMappingDataByPermissionId", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryClientMappingData(java.lang.String a0) {
            record("queryClientMappingData", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String addConfigData(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, int a4, java.lang.String a5, int a6) {
            record("addConfigData", new Object[] {a0, a1, a2, a3, a4, a5, a6});
            return null;
        }
        @Override
        public java.lang.String addConfigDataJson(java.lang.String a0) {
            record("addConfigDataJson", new Object[] {a0});
            return null;
        }
        @Override
        public boolean deleteConfigDataByConfigId(java.lang.String a0) {
            record("deleteConfigDataByConfigId", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteConfigDataByPkg(java.lang.String a0) {
            record("deleteConfigDataByPkg", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteConfigData(java.lang.String a0) {
            record("deleteConfigData", new Object[] {a0});
            return false;
        }
        @Override
        public boolean updateDefaultConfigData(java.lang.String a0, java.lang.String a1) {
            record("updateDefaultConfigData", new Object[] {a0, a1});
            return false;
        }
        @Override
        public boolean updateConfigData(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, int a4, java.lang.String a5, int a6) {
            record("updateConfigData", new Object[] {a0, a1, a2, a3, a4, a5, a6});
            return false;
        }
        @Override
        public boolean updateConfigDataJson(java.lang.String a0) {
            record("updateConfigDataJson", new Object[] {a0});
            return false;
        }
        @Override
        public java.lang.String queryConfigDataByConfigId(java.lang.String a0) {
            record("queryConfigDataByConfigId", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryConfigDataByConfigName(java.lang.String a0) {
            record("queryConfigDataByConfigName", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryConfigData(java.lang.String a0) {
            record("queryConfigData", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String addConfigGroupData(int a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, java.lang.String a4, int a5) {
            record("addConfigGroupData", new Object[] {a0, a1, a2, a3, a4, a5});
            return null;
        }
        @Override
        public java.lang.String addConfigGroupDataJson(java.lang.String a0) {
            record("addConfigGroupDataJson", new Object[] {a0});
            return null;
        }
        @Override
        public boolean deleteConfigGroupDataByConfigGroupId(java.lang.String a0) {
            record("deleteConfigGroupDataByConfigGroupId", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteConfigGroupData(java.lang.String a0) {
            record("deleteConfigGroupData", new Object[] {a0});
            return false;
        }
        @Override
        public boolean updateConfigGroupData(java.lang.String a0, int a1) {
            record("updateConfigGroupData", new Object[] {a0, a1});
            return false;
        }
        @Override
        public boolean updateConfigGroupData1(java.lang.String a0, int a1, java.lang.String a2, java.lang.String a3, java.lang.String a4, java.lang.String a5, int a6) {
            record("updateConfigGroupData1", new Object[] {a0, a1, a2, a3, a4, a5, a6});
            return false;
        }
        @Override
        public boolean updateConfigGroupDataJson(java.lang.String a0) {
            record("updateConfigGroupDataJson", new Object[] {a0});
            return false;
        }
        @Override
        public java.lang.String queryConfigGroupDataByConfigGroupId(java.lang.String a0) {
            record("queryConfigGroupDataByConfigGroupId", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryConfigGroupData(java.lang.String a0) {
            record("queryConfigGroupData", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String addPermissionData(java.lang.String a0, int a1, java.lang.String a2, int a3, int a4, java.lang.String a5, int a6) {
            record("addPermissionData", new Object[] {a0, a1, a2, a3, a4, a5, a6});
            return null;
        }
        @Override
        public java.lang.String addPermissionDataJson(java.lang.String a0) {
            record("addPermissionDataJson", new Object[] {a0});
            return null;
        }
        @Override
        public boolean deletePermissionDataByPermissionId(java.lang.String a0) {
            record("deletePermissionDataByPermissionId", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deletePermissionData(java.lang.String a0) {
            record("deletePermissionData", new Object[] {a0});
            return false;
        }
        @Override
        public boolean updatePermissionData(java.lang.String a0, byte a1) {
            record("updatePermissionData", new Object[] {a0, a1});
            return false;
        }
        @Override
        public boolean updatePermissionData1(java.lang.String a0, java.lang.String a1, int a2, java.lang.String a3, int a4, int a5, java.lang.String a6, int a7) {
            record("updatePermissionData1", new Object[] {a0, a1, a2, a3, a4, a5, a6, a7});
            return false;
        }
        @Override
        public boolean updatePermissionDataJson(java.lang.String a0) {
            record("updatePermissionDataJson", new Object[] {a0});
            return false;
        }
        @Override
        public java.lang.String queryPermissionDataByPermissionId(java.lang.String a0) {
            record("queryPermissionDataByPermissionId", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryPermissionData(java.lang.String a0) {
            record("queryPermissionData", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String addRuleData(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, int a4) {
            record("addRuleData", new Object[] {a0, a1, a2, a3, a4});
            return null;
        }
        @Override
        public java.lang.String addRuleDataJson(java.lang.String a0) {
            record("addRuleDataJson", new Object[] {a0});
            return null;
        }
        @Override
        public boolean deleteRuleDataByRuleId(java.lang.String a0) {
            record("deleteRuleDataByRuleId", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteRuleData(java.lang.String a0) {
            record("deleteRuleData", new Object[] {a0});
            return false;
        }
        @Override
        public boolean updateRuleData(java.lang.String a0, java.lang.String a1, java.lang.String a2, java.lang.String a3, int a4) {
            record("updateRuleData", new Object[] {a0, a1, a2, a3, a4});
            return false;
        }
        @Override
        public boolean updateRuleDataJson(java.lang.String a0) {
            record("updateRuleDataJson", new Object[] {a0});
            return false;
        }
        @Override
        public java.lang.String queryRuleDataByRuleId(java.lang.String a0) {
            record("queryRuleDataByRuleId", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryRuleData(java.lang.String a0) {
            record("queryRuleData", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String addLogTableData(java.lang.String a0, int a1, int a2) {
            record("addLogTableData", new Object[] {a0, a1, a2});
            return null;
        }
        @Override
        public java.lang.String addLogTableDataJson(java.lang.String a0) {
            record("addLogTableDataJson", new Object[] {a0});
            return null;
        }
        @Override
        public boolean deleteLogTableDataByLogId(java.lang.String a0) {
            record("deleteLogTableDataByLogId", new Object[] {a0});
            return false;
        }
        @Override
        public boolean deleteLogTableData(java.lang.String a0) {
            record("deleteLogTableData", new Object[] {a0});
            return false;
        }
        @Override
        public boolean updateLogTableData(java.lang.String a0, int a1, int a2) {
            record("updateLogTableData", new Object[] {a0, a1, a2});
            return false;
        }
        @Override
        public boolean updateLogTableDataJson(java.lang.String a0) {
            record("updateLogTableDataJson", new Object[] {a0});
            return false;
        }
        @Override
        public java.lang.String queryLogTableDataByLogId(java.lang.String a0) {
            record("queryLogTableDataByLogId", new Object[] {a0});
            return null;
        }
        @Override
        public java.lang.String queryLogTableData(java.lang.String a0) {
            record("queryLogTableData", new Object[] {a0});
            return null;
        }
        @Override
        public boolean saveConfigData(java.lang.String a0) {
            record("saveConfigData", new Object[] {a0});
            return false;
        }
    }

    static final class ImplIBluetoothPxr extends com.pxr.bluetooth.IBluetoothPxr.Stub {
        @Override
        public void registerDeviceStateCallback(com.pxr.bluetooth.IBluetoothPxrDeviceCallback a0) {
            record("registerDeviceStateCallback", new Object[] {a0});
        }
        @Override
        public com.pxr.bluetooth.BluetoothPxrDeviceProperty[] getConnectedDevices() {
            record("getConnectedDevices", new Object[] {});
            return null;
        }
    }

    static final class ImplIBluetoothPxrDeviceCallback extends com.pxr.bluetooth.IBluetoothPxrDeviceCallback.Stub {
        @Override
        public void onDeviceConnectionStateChanged(com.pxr.bluetooth.BluetoothPxrDeviceProperty a0, int a1, int a2) {
            record("onDeviceConnectionStateChanged", new Object[] {a0, a1, a2});
        }
        @Override
        public void onDeviceBondStateChanged(com.pxr.bluetooth.BluetoothPxrDeviceProperty a0, int a1, int a2) {
            record("onDeviceBondStateChanged", new Object[] {a0, a1, a2});
        }
    }

    static final class ImplILinkLayerQualityListener extends com.pxr.net.ILinkLayerQualityListener.Stub {
        @Override
        public void onLinkLayerQualityChanged(com.pxr.net.LinkLayerQuality a0) {
            record("onLinkLayerQualityChanged", new Object[] {a0});
        }
        @Override
        public void onLinkLayerLevelChanged(com.pxr.net.LinkLayerQuality a0) {
            record("onLinkLayerLevelChanged", new Object[] {a0});
        }
        @Override
        public void onAverLinkLayerLevelChanged(com.pxr.net.LinkLayerQuality a0) {
            record("onAverLinkLayerLevelChanged", new Object[] {a0});
        }
    }

    static final class ImplINetworkQualityListener extends com.pxr.net.INetworkQualityListener.Stub {
        @Override
        public void onNetworkQualityChanged(com.pxr.net.NetworkQuality a0) {
            record("onNetworkQualityChanged", new Object[] {a0});
        }
    }

    static final class ImplIPxrNetworkManager extends com.pxr.net.IPxrNetworkManager.Stub {
        @Override
        public boolean registerNetworkQualityChangedListener(java.lang.String a0, int a1, com.pxr.net.INetworkQualityListener a2) {
            record("registerNetworkQualityChangedListener", new Object[] {a0, a1, a2});
            return false;
        }
        @Override
        public boolean unregisterNetworkQualityChangedListener(java.lang.String a0, com.pxr.net.INetworkQualityListener a1) {
            record("unregisterNetworkQualityChangedListener", new Object[] {a0, a1});
            return false;
        }
        @Override
        public boolean registerLinkLayerQualityChangedListener(java.lang.String a0, com.pxr.net.ILinkLayerQualityListener a1) {
            record("registerLinkLayerQualityChangedListener", new Object[] {a0, a1});
            return false;
        }
        @Override
        public boolean unregisterLinkLayerQualityChangedListener(java.lang.String a0, com.pxr.net.ILinkLayerQualityListener a1) {
            record("unregisterLinkLayerQualityChangedListener", new Object[] {a0, a1});
            return false;
        }
        @Override
        public void updateLinkLayerQuality(java.lang.String a0, com.pxr.net.PxrWifiConnectionInfo a1) {
            record("updateLinkLayerQuality", new Object[] {a0, a1});
        }
        @Override
        public com.pxr.net.LinkLayerQuality getLinkLayerQuality(java.lang.String a0) {
            record("getLinkLayerQuality", new Object[] {a0});
            return null;
        }
        @Override
        public com.pxr.net.LinkLayerQuality getAverageLinkLayerQuality(java.lang.String a0) {
            record("getAverageLinkLayerQuality", new Object[] {a0});
            return null;
        }
    }

    static final class ImplIScreenCaptureInterface extends com.pxr.pxrapi.IScreenCaptureInterface.Stub {
        @Override
        public int startCapture(android.view.Surface a0, int a1, int a2, int a3) {
            record("startCapture", new Object[] {a0, a1, a2, a3});
            return 0;
        }
        @Override
        public void stopCapture() {
            record("stopCapture", new Object[] {});
        }
    }
}
